CREATE DATABASE IF NOT EXISTS 480base;

USE 480base;

CREATE TABLE airportdata (
    iata      	VARCHAR(3) 		PRIMARY KEY,
    city 		VARCHAR(100),
    state 	   	VARCHAR(100),
    country  	VARCHAR(100)
);

CREATE TABLE managebooking (
	id			BIGINT AUTO_INCREMENT 			PRIMARY KEY,
    passenger	VARCHAR(100),
    flight		VARCHAR(100),
    confirm		VARCHAR(100)
);

DROP TABLE managebooking;

INSERT INTO managebooking (id, passenger, flight, confirm) VALUES
(1, 'John Doe', 'NY to LA', 'Confirmed');


INSERT INTO airportData (iata, city, state, country) VALUES 
('ICY', 'Icy Bay', 'Alaska', 'US'),
('HGZ', 'Hogatza', 'Alaska', 'US'),
('BYW', 'Blakely Island', 'Washington', 'US'),
('BDF', 'Bradford', 'Illinois', 'US'),
('BCS', 'Belle Chasse', 'Louisiana', 'US'),
('BWL', 'Blackwell', 'Oklahoma', 'US'),
('DUF', 'Corolla', 'North Carolina', 'US'),
('FOB', 'Fort Bragg', 'California', 'US'),
('ALX', 'Alexander City', 'Alabama', 'US'),
('CEX', 'Chena Hot Springs', 'Alaska', 'US'),
('HED', 'Herendeen Bay', 'Alaska', 'US'),
('TWE', 'Taylor', 'Alaska', 'US'),
('CDL', 'Candle', 'Alaska', 'US'),
('BSZ', 'Egegik', 'Alaska', 'US'),
('BSW', 'Boswell Bay', 'Alaska', 'US'),
('YZZ', 'Trail', 'British Columbia', 'CA'),
('YAA', 'Anahim Lake', 'British Columbia', 'CA'),
('DGF', 'Douglas Lake', 'British Columbia', 'CA'),
('JHL', 'Albian Village', 'Alberta', 'CA'),
('DUQ', 'Duncan', 'British Columbia', 'CA'),
('ZEL', 'Bella Bella', 'British Columbia', 'CA'),
('YWM', 'Williams Harbour', 'Newfoundland and Labrador', 'CA'),
('YFX', 'St. Lewis', 'Newfoundland and Labrador', 'CA'),
('YHA', 'Port Hope Simpson', 'Newfoundland and Labrador', 'CA'),
('YRG', 'Rigolet', 'Newfoundland and Labrador', 'CA'),
('DVK', 'Diavik', 'Northwest Territories', 'CA'),
('YCK', 'Colville Lake', 'Northwest Territories', 'CA'),
('YLE', 'Whati', 'Northwest Territories', 'CA'),
('NML', 'Fort McMurray', 'Alberta', 'CA'),
('ZSP', 'St. Paul', 'Alberta', 'CA'),
('DAS', 'Great Bear Lake', 'Northwest Territories', 'CA'),
('YFI', 'Suncor Energy Site', 'Alberta', 'CA'),
('SUR', 'Summer Beaver', 'Ontario', 'CA'),
('YAX', 'Angling Lake', 'Ontario', 'CA'),
('WNN', 'Wunnumin Lake', 'Ontario', 'CA'),
('YNO', 'North Spirit Lake', 'Ontario', 'CA'),
('XBE', 'Bearskin Lake', 'Ontario', 'CA'),
('KIF', 'Kingfisher Lake', 'Ontario', 'CA'),
('YOG', 'Ogoki Post', 'Ontario', 'CA'),
('YEB', 'Bar River', 'Ontario', 'CA'),
('YHP', 'Poplar Hill', 'Ontario', 'CA'),
('YNX', 'Snap Lake', 'Northwest Territories', 'CA'),
('YKU', 'Chisasibi', 'Quebec', 'CA'),
('ZTB', 'Tete-a-la-Baleine', 'Quebec', 'CA'),
('YAU', 'Kattiniq', 'Quebec', 'CA'),
('ZLT', 'La Tabatiere', 'Quebec', 'CA'),
('YAC', 'Cat Lake', 'Ontario', 'CA'),
('YAR', 'La Grande-3', 'Quebec', 'CA'),
('YAG', 'Fort Frances', 'Ontario', 'CA'),
('YAH', 'La Grande-4', 'Quebec', 'CA'),
('YAL', 'Alert Bay', 'British Columbia', 'CA'),
('YAM', 'Sault Ste Marie', 'Ontario', 'CA'),
('XKS', 'Kasabonika', 'Ontario', 'CA'),
('YKG', 'Kangirsuk', 'Quebec', 'CA'),
('YAT', 'Attawapiskat', 'Ontario', 'CA'),
('YAW', 'Halifax', 'Nova Scotia', 'CA'),
('YAY', 'St. Anthony', 'Newfoundland and Labrador', 'CA'),
('YAZ', 'Tofino', 'British Columbia', 'CA'),
('YBA', 'Banff', 'Alberta', 'CA'),
('YBB', 'Kugaaruk', 'Nunavut', 'CA'),
('YBC', 'Baie-Comeau', 'Quebec', 'CA'),
('QBC', 'Bella Coola', 'British Columbia', 'CA'),
('YBE', 'Uranium City', 'Saskatchewan', 'CA'),
('YBY', 'Bonnyville', 'Alberta', 'CA'),
('YBG', 'Bagotville', 'Quebec', 'CA'),
('YBK', 'Baker Lake', 'Nunavut', 'CA'),
('YBL', 'Campbell River', 'British Columbia', 'CA'),
('XTL', 'Tadoule Lake', 'Manitoba', 'CA'),
('YBR', 'Brandon', 'Manitoba', 'CA'),
('YBT', 'Brochet', 'Manitoba', 'CA'),
('YBV', 'Berens River', 'Manitoba', 'CA'),
('YBX', 'Lourdes-De-Blanc-Sablon', 'Quebec', 'CA'),
('YRF', 'Cartwright', 'Newfoundland and Labrador', 'CA'),
('YCB', 'Cambridge Bay', 'Nunavut', 'CA'),
('YCC', 'Cornwall', 'Quebec', 'CA'),
('YCD', 'Nanaimo', 'British Columbia', 'CA'),
('YCE', 'Centralia', 'Ontario', 'CA'),
('YCG', 'Castlegar', 'British Columbia', 'CA'),
('YCH', 'Miramichi', 'New Brunswick', 'CA'),
('XCM', 'Chatham-Kent', 'Ontario', 'CA'),
('YCL', 'Charlo', 'New Brunswick', 'CA'),
('YCN', 'Cochrane', 'Ontario', 'CA'),
('YCO', 'Kugluktuk', 'Nunavut', 'CA'),
('YCQ', 'Chetwynd', 'British Columbia', 'CA'),
('YCR', 'Cross Lake', 'Manitoba', 'CA'),
('YCS', 'Chesterfield Inlet', 'Nunavut', 'CA'),
('YCT', 'Coronation', 'Alberta', 'CA'),
('YCW', 'Chilliwack', 'British Columbia', 'CA'),
('YCY', 'Clyde River', 'Nunavut', 'CA'),
('YCZ', 'Fairmont Hot Springs', 'British Columbia', 'CA'),
('YDA', 'Dawson City', 'Yukon', 'CA'),
('YDB', 'Burwash', 'Yukon', 'CA'),
('YDF', 'Deer Lake', 'Newfoundland and Labrador', 'CA'),
('YDL', 'Dease Lake', 'British Columbia', 'CA'),
('YDM', 'Ross River', 'Yukon', 'CA'),
('YDN', 'Dauphin', 'Manitoba', 'CA'),
('YDO', 'Dolbeau-St-Felicien', 'Quebec', 'CA'),
('YDP', 'Nain', 'Newfoundland and Labrador', 'CA'),
('YDQ', 'Dawson Creek', 'British Columbia', 'CA'),
('YEG', 'Edmonton', 'Alberta', 'CA'),
('YEK', 'Arviat', 'Nunavut', 'CA'),
('YEL', 'Elliot Lake', 'Ontario', 'CA'),
('YEM', 'Manitowaning', 'Ontario', 'CA'),
('YEN', 'Estevan', 'Saskatchewan', 'CA'),
('YER', 'Fort Severn', 'Ontario', 'CA'),
('YET', 'Edson', 'Alberta', 'CA'),
('YEU', 'Eureka', 'Nunavut', 'CA'),
('YEV', 'Inuvik', 'Northwest Territories', 'CA'),
('YEY', 'Amos', 'Quebec', 'CA'),
('YFA', 'Fort Albany', 'Ontario', 'CA'),
('YFB', 'Iqaluit', 'Nunavut', 'CA'),
('YFC', 'Fredericton', 'New Brunswick', 'CA'),
('YFE', 'Forestville', 'Quebec', 'CA'),
('YFH', 'Fort Hope', 'Ontario', 'CA'),
('YTM', 'Riviere Rouge', 'Quebec', 'CA'),
('YFO', 'Flin Flon', 'Manitoba', 'CA'),
('YFR', 'Fort Resolution', 'Northwest Territories', 'CA'),
('YFS', 'Fort Simpson', 'Northwest Territories', 'CA'),
('YMN', 'Makkovik', 'Newfoundland and Labrador', 'CA'),
('YGB', 'Texada', 'British Columbia', 'CA'),
('YGD', 'Goderich', 'Ontario', 'CA'),
('YGH', 'Fort Good Hope', 'Northwest Territories', 'CA'),
('YGK', 'Kingston', 'Ontario', 'CA'),
('YGL', 'La Grande Riviere', 'Quebec', 'CA'),
('YGM', 'Gimli', 'Manitoba', 'CA'),
('YGO', 'Gods Lake Narrows', 'Manitoba', 'CA'),
('YGP', 'Gaspe', 'Quebec', 'CA'),
('YGQ', 'Geraldton', 'Ontario', 'CA'),
('YGR', 'Iles-de-la-Madeleine', 'Quebec', 'CA'),
('YGT', 'Igloolik', 'Nunavut', 'CA'),
('YGV', 'Havre St-Pierre', 'Quebec', 'CA'),
('YGW', 'Kuujjuarapik', 'Quebec', 'CA'),
('YGX', 'Gillam', 'Manitoba', 'CA'),
('YGZ', 'Grise Fiord', 'Nunavut', 'CA'),
('YQC', 'Quaqtaq', 'Quebec', 'CA'),
('YHB', 'Hudson Bay', 'Saskatchewan', 'CA'),
('YHD', 'Dryden', 'Ontario', 'CA'),
('YHE', 'Hope', 'British Columbia', 'CA'),
('YHF', 'Hearst', 'Ontario', 'CA'),
('YNS', 'Nemiscau', 'Quebec', 'CA'),
('YHI', 'Ulukhaktok', 'Northwest Territories', 'CA'),
('YHK', 'Gjoa Haven', 'Nunavut', 'CA'),
('YHM', 'Hamilton', 'Ontario', 'CA'),
('YHN', 'Hornepayne', 'Ontario', 'CA'),
('YHO', 'Hopedale', 'Newfoundland and Labrador', 'CA'),
('YHR', 'Chevery', 'Quebec', 'CA'),
('YHT', 'Haines Junction', 'Yukon', 'CA'),
('YHU', 'Montreal', 'Quebec', 'CA'),
('YHY', 'Hay River', 'Northwest Territories', 'CA'),
('YHZ', 'Halifax', 'Nova Scotia', 'CA'),
('YIB', 'Atikokan', 'Ontario', 'CA'),
('YDG', 'Digby', 'Nova Scotia', 'CA'),
('YIF', 'St-Augustin', 'Quebec', 'CA'),
('YIK', 'Ivujivik', 'Quebec', 'CA'),
('YIO', 'Pond Inlet', 'Nunavut', 'CA'),
('YIV', 'Island Lake', 'Manitoba', 'CA'),
('YJA', 'Jasper', 'Alberta', 'CA'),
('YJF', 'Fort Liard', 'Northwest Territories', 'CA'),
('YJN', 'St Jean', 'Quebec', 'CA'),
('YJT', 'Stephenville', 'Newfoundland and Labrador', 'CA'),
('YKA', 'Kamloops', 'British Columbia', 'CA'),
('YKC', 'Collins Bay', 'Saskatchewan', 'CA'),
('LAK', 'Aklavik', 'Northwest Territories', 'CA'),
('YKF', 'Kitchener', 'Ontario', 'CA'),
('YWB', 'Kangiqsujuaq', 'Quebec', 'CA'),
('YKJ', 'Key Lake', 'Saskatchewan', 'CA'),
('YKL', 'Schefferville', 'Quebec', 'CA'),
('AKV', 'Akulivik', 'Quebec', 'CA'),
('YKQ', 'Waskaganish', 'Quebec', 'CA'),
('YKX', 'Kirkland Lake', 'Ontario', 'CA'),
('YKY', 'Kindersley', 'Saskatchewan', 'CA'),
('YKZ', 'Toronto', 'Ontario', 'CA'),
('YPJ', 'Aupaluk', 'Quebec', 'CA'),
('YLB', 'Lac La Biche', 'Alberta', 'CA'),
('YLC', 'Kimmirut', 'Nunavut', 'CA'),
('YLD', 'Chapleau', 'Ontario', 'CA'),
('YLH', 'Lansdowne House', 'Ontario', 'CA'),
('YLJ', 'Meadow Lake', 'Saskatchewan', 'CA'),
('YSG', 'Lutselk\'e', 'Northwest Territories', 'CA'),
('YLL', 'Lloydminster', 'Saskatchewan', 'CA'),
('YLQ', 'La Tuque', 'Quebec', 'CA'),
('YLR', 'Leaf Rapids', 'Manitoba', 'CA'),
('YLK', 'Barrie-Orillia', 'Ontario', 'CA'),
('YLT', 'Alert', 'Nunavut', 'CA'),
('XGR', 'Kangiqsualujjuaq', 'Quebec', 'CA'),
('YLW', 'Kelowna', 'British Columbia', 'CA'),
('YMA', 'Mayo', 'Yukon', 'CA'),
('YME', 'Matane', 'Quebec', 'CA'),
('YMG', 'Manitouwadge', 'Ontario', 'CA'),
('YMH', 'Mary\'s Harbour', 'Newfoundland and Labrador', 'CA'),
('YMJ', 'Moose Jaw', 'Saskatchewan', 'CA'),
('YML', 'Charlevoix', 'Quebec', 'CA'),
('YMM', 'Fort McMurray', 'Alberta', 'CA'),
('YMO', 'Moosonee', 'Ontario', 'CA'),
('YMT', 'Chibougamau', 'Quebec', 'CA'),
('YUD', 'Umiujaq', 'Quebec', 'CA'),
('YMW', 'Maniwaki', 'Quebec', 'CA'),
('YMX', 'Montreal', 'Quebec', 'CA'),
('YNA', 'Natashquan', 'Quebec', 'CA'),
('YNC', 'Wemindji', 'Quebec', 'CA'),
('YND', 'Gatineau', 'Quebec', 'CA'),
('YNE', 'Norway House', 'Manitoba', 'CA'),
('YNH', 'Hudson\'s Hope', 'British Columbia', 'CA'),
('YLY', 'Langley', 'British Columbia', 'CA'),
('YNL', 'Points North Landing', 'Saskatchewan', 'CA'),
('YNM', 'Matagami', 'Quebec', 'CA'),
('YNN', 'Nejanilini Lake', 'Manitoba', 'CA'),
('HZP', 'Fort Mackay', 'Alberta', 'CA'),
('YOA', 'Ekati', 'Northwest Territories', 'CA'),
('YOC', 'Old Crow', 'Yukon', 'CA'),
('YOD', 'Cold Lake', 'Alberta', 'CA'),
('YOH', 'Oxford House', 'Manitoba', 'CA'),
('YOJ', 'High Level', 'Alberta', 'CA'),
('YOO', 'Oshawa', 'Ontario', 'CA'),
('YOP', 'Rainbow Lake', 'Alberta', 'CA'),
('YOS', 'Owen Sound', 'Ontario', 'CA'),
('YOW', 'Ottawa', 'Ontario', 'CA'),
('YPA', 'Prince Albert', 'Saskatchewan', 'CA'),
('YPC', 'Paulatuk', 'Northwest Territories', 'CA'),
('YPS', 'Port Hawkesbury', 'Nova Scotia', 'CA'),
('YPE', 'Peace River', 'Alberta', 'CA'),
('YPG', 'Portage', 'Manitoba', 'CA'),
('YPH', 'Inukjuak', 'Quebec', 'CA'),
('YPL', 'Pickle Lake', 'Ontario', 'CA'),
('YPM', 'Pikangikum', 'Ontario', 'CA'),
('YPN', 'Port-Menier', 'Quebec', 'CA'),
('YPO', 'Peawanuck', 'Ontario', 'CA'),
('YPQ', 'Peterborough', 'Ontario', 'CA'),
('YPR', 'Prince Rupert', 'British Columbia', 'CA'),
('YPW', 'Powell River', 'British Columbia', 'CA'),
('YPX', 'Puvirnituq', 'Quebec', 'CA'),
('YPY', 'Fort Chipewyan', 'Alberta', 'CA'),
('YPZ', 'Burns Lake', 'British Columbia', 'CA'),
('YQA', 'Muskoka', 'Ontario', 'CA'),
('YQB', 'Quebec', 'Quebec', 'CA'),
('YQD', 'The Pas', 'Manitoba', 'CA'),
('YQF', 'Red Deer', 'Alberta', 'CA'),
('YQG', 'Windsor', 'Ontario', 'CA'),
('YQH', 'Watson Lake', 'Yukon', 'CA'),
('YQI', 'Yarmouth', 'Nova Scotia', 'CA'),
('YQK', 'Kenora', 'Ontario', 'CA'),
('YQL', 'Lethbridge', 'Alberta', 'CA'),
('YQM', 'Moncton', 'New Brunswick', 'CA'),
('YQN', 'Nakina', 'Ontario', 'CA'),
('YQQ', 'Comox', 'British Columbia', 'CA'),
('YQR', 'Regina', 'Saskatchewan', 'CA'),
('YQS', 'St Thomas', 'Ontario', 'CA'),
('YQT', 'Thunder Bay', 'Ontario', 'CA'),
('YQU', 'Grande Prairie', 'Alberta', 'CA'),
('YQV', 'Yorkton', 'Saskatchewan', 'CA'),
('YQW', 'North Battleford', 'Saskatchewan', 'CA'),
('YQX', 'Gander', 'Newfoundland and Labrador', 'CA'),
('YQY', 'Sydney', 'Nova Scotia', 'CA'),
('YQZ', 'Quesnel', 'British Columbia', 'CA'),
('YRA', 'Gameti', 'Northwest Territories', 'CA'),
('YRB', 'Resolute Bay', 'Nunavut', 'CA'),
('YRI', 'Riviere-du-Loup', 'Quebec', 'CA'),
('YRJ', 'Roberval', 'Quebec', 'CA'),
('YRL', 'Red Lake', 'Ontario', 'CA'),
('YRM', 'Rocky Mountain House', 'Alberta', 'CA'),
('YRO', 'Ottawa', 'Ontario', 'CA'),
('YRP', 'Carp', 'Ontario', 'CA'),
('YRQ', 'Trois-Rivieres', 'Quebec', 'CA'),
('YRS', 'Red Sucker Lake', 'Manitoba', 'CA'),
('YRT', 'Rankin Inlet', 'Nunavut', 'CA'),
('YRV', 'Revelstoke', 'British Columbia', 'CA'),
('YSB', 'Sudbury', 'Ontario', 'CA'),
('YSC', 'Sherbrooke', 'Quebec', 'CA'),
('YSE', 'Squamish', 'British Columbia', 'CA'),
('YSF', 'Stony Rapids', 'Saskatchewan', 'CA'),
('YSH', 'Smiths Falls', 'Ontario', 'CA'),
('YSJ', 'Saint John', 'New Brunswick', 'CA'),
('YSK', 'Sanikiluaq', 'Nunavut', 'CA'),
('YSL', 'St Leonard', 'New Brunswick', 'CA'),
('YSM', 'Fort Smith', 'Northwest Territories', 'CA'),
('YCM', 'St Catharines', 'Ontario', 'CA'),
('YSP', 'Marathon', 'Ontario', 'CA'),
('YST', 'St. Theresa Point', 'Manitoba', 'CA'),
('YSU', 'Summerside', 'Prince Edward Island', 'CA'),
('YSY', 'Sachs Harbour', 'Northwest Territories', 'CA'),
('YTA', 'Pembroke', 'Ontario', 'CA'),
('YTE', 'Cape Dorset', 'Nunavut', 'CA'),
('YTF', 'Alma', 'Quebec', 'CA'),
('YTH', 'Thompson', 'Manitoba', 'CA'),
('YTL', 'Big Trout Lake', 'Ontario', 'CA'),
('YTQ', 'Tasiujaq', 'Quebec', 'CA'),
('YTR', 'Trenton', 'Ontario', 'CA'),
('YTS', 'Timmins', 'Ontario', 'CA'),
('YTZ', 'Toronto', 'Ontario', 'CA'),
('YUB', 'Tuktoyaktuk', 'Northwest Territories', 'CA'),
('YUL', 'Montreal', 'Quebec', 'CA'),
('YUT', 'Repulse Bay', 'Nunavut', 'CA'),
('YUX', 'Hall Beach', 'Nunavut', 'CA'),
('YUY', 'Rouyn-Noranda', 'Quebec', 'CA'),
('YVB', 'Bonaventure', 'Quebec', 'CA'),
('YVC', 'La Ronge', 'Saskatchewan', 'CA'),
('YVG', 'Vermilion', 'Alberta', 'CA'),
('YVE', 'Vernon', 'British Columbia', 'CA'),
('YVM', 'Qikiqtarjuaq', 'Nunavut', 'CA'),
('YVO', 'Val-d\'Or', 'Quebec', 'CA'),
('YVP', 'Kuujjuaq', 'Quebec', 'CA'),
('YVQ', 'Norman Wells', 'Northwest Territories', 'CA'),
('YVR', 'Vancouver', 'British Columbia', 'CA'),
('YVT', 'Buffalo Narrows', 'Saskatchewan', 'CA'),
('YVV', 'Wiarton', 'Ontario', 'CA'),
('YVZ', 'Deer Lake', 'Ontario', 'CA'),
('YWA', 'Petawawa', 'Ontario', 'CA'),
('YFJ', 'Wekweeti', 'Northwest-Territories', 'CA'),
('YWG', 'Winnipeg', 'Manitoba', 'CA'),
('YWJ', 'Deline', 'Northwest-Territories', 'CA'),
('YWK', 'Wabush', 'Newfoundland-and-Labrador', 'CA'),
('YWL', 'Williams Lake', 'British-Columbia', 'CA'),
('YWP', 'Webequie', 'Ontario', 'CA'),
('YWY', 'Wrigley', 'Northwest-Territories', 'CA'),
('YXC', 'Cranbrook', 'British-Columbia', 'CA'),
('YXD', 'Edmonton', 'Alberta', 'CA'),
('YXE', 'Saskatoon', 'Saskatchewan', 'CA'),
('YXH', 'Medicine Hat', 'Alberta', 'CA'),
('YXJ', 'Fort St.John', 'British-Columbia', 'CA'),
('YXK', 'Rimouski', 'Quebec', 'CA'),
('YXL', 'Sioux Lookout', 'Ontario', 'CA'),
('YXN', 'Whale Cove', 'Nunavut', 'CA'),
('YXP', 'Pangnirtung', 'Nunavut', 'CA'),
('YXQ', 'Beaver Creek', 'Yukon', 'CA'),
('YXR', 'Earlton', 'Ontario', 'CA'),
('YXS', 'Prince George', 'British-Columbia', 'CA'),
('YXT', 'Terrace', 'British-Columbia', 'CA'),
('YXU', 'London', 'Ontario', 'CA'),
('YXX', 'Abbotsford', 'British-Columbia', 'CA'),
('YXY', 'Whitehorse', 'Yukon', 'CA'),
('YXZ', 'Wawa', 'Ontario', 'CA'),
('YYB', 'North Bay', 'Ontario', 'CA'),
('YYC', 'Calgary', 'Alberta', 'CA'),
('YYD', 'Smithers', 'British-Columbia', 'CA'),
('YYE', 'Fort Nelson', 'British-Columbia', 'CA'),
('YYF', 'Penticton', 'British-Columbia', 'CA'),
('YYG', 'Charlottetown', 'Newfoundland-and-Labrador', 'CA'),
('YYH', 'Taloyoak', 'Nunavut', 'CA'),
('YYJ', 'Victoria', 'British-Columbia', 'CA'),
('YYL', 'Lynn Lake', 'Manitoba', 'CA'),
('YYM', 'Cowley', 'Alberta', 'CA'),
('YYN', 'Swift Current', 'Saskatchewan', 'CA'),
('YYQ', 'Churchill', 'Manitoba', 'CA'),
('YYR', 'Goose Bay', 'Newfoundland-and-Labrador', 'CA'),
('YYT', 'St. John\'s', 'Newfoundland-and-Labrador', 'CA'),
('YYU', 'Kapuskasing', 'Ontario', 'CA'),
('YYW', 'Armstrong', 'Ontario', 'CA'),
('YYY', 'Mont-Joli', 'Quebec', 'CA'),
('YYZ', 'Toronto', 'Ontario', 'CA'),
('YZD', 'Toronto', 'Ontario', 'CA'),
('YZE', 'Gore Bay', 'Ontario', 'CA'),
('YZF', 'Yellowknife', 'Northwest-Territories', 'CA'),
('YZG', 'Salluit', 'Quebec', 'CA'),
('YZH', 'Slave Lake', 'Alberta', 'CA'),
('YZP', 'Sandspit', 'British-Columbia', 'CA'),
('YZR', 'Sarnia', 'Ontario', 'CA'),
('YZS', 'Coral Harbour', 'Nunavut', 'CA'),
('YZT', 'Port Hardy', 'British-Columbia', 'CA'),
('YZU', 'Whitecourt', 'Alberta', 'CA'),
('YZV', 'Sept-Iles', 'Quebec', 'CA'),
('YZW', 'Teslin', 'Yukon', 'CA'),
('YZX', 'Greenwood', 'Nova-Scotia', 'CA'),
('YZY', 'Mackenzie', 'British-Columbia', 'CA'),
('ZAC', 'York Landing', 'Manitoba', 'CA'),
('YSN', 'Salmon Arm', 'British-Columbia', 'CA'),
('YDT', 'Burlington', 'Ontario', 'CA'),
('ZBD', 'Boundary Bay', 'British-Columbia', 'CA'),
('ILF', 'Ilford', 'Manitoba', 'CA'),
('ZBF', 'Bathurst', 'New-Brunswick', 'CA'),
('ZBM', 'Bromont', 'Quebec', 'CA'),
('ZEE', 'Kelsey', 'Manitoba', 'CA'),
('ZEM', 'Eastmain River', 'Quebec', 'CA'),
('ZFA', 'Faro', 'Yukon', 'CA'),
('ZFD', 'Fond-Du-Lac', 'Saskatchewan', 'CA'),
('ZFG', 'Pukatawagan', 'Manitoba', 'CA'),
('ZFM', 'Fort Mcpherson', 'Northwest-Territories', 'CA'),
('ZFN', 'Tulita', 'Northwest-Territories', 'CA'),
('ZGF', 'Grand Forks', 'British-Columbia', 'CA'),
('ZGI', 'Gods River', 'Manitoba', 'CA'),
('ZGR', 'Little Grand Rapids', 'Manitoba', 'CA'),
('ZHP', 'High Prairie', 'Alberta', 'CA'),
('ZJG', 'Jenpeg', 'Manitoba', 'CA'),
('ZJN', 'Swan River', 'Manitoba', 'CA'),
('ZKE', 'Kashechewan', 'Ontario', 'CA'),
('YTD', 'Thicket Portage', 'Manitoba', 'CA'),
('MSA', 'Muskrat Dam', 'Ontario', 'CA'),
('ZMH', '108 Mile', 'British-Columbia', 'CA'),
('PIW', 'Pikwitonei', 'Manitoba', 'CA'),
('ZMT', 'Masset', 'British-Columbia', 'CA'),
('ZNG', 'Poplar River', 'Manitoba', 'CA'),
('ZPB', 'Sachigo Lake', 'Ontario', 'CA'),
('WPC', 'Pincher Creek', 'Alberta', 'CA'),
('ZPO', 'Pinehouse Lake', 'Saskatchewan', 'CA'),
('ZRJ', 'Round Lake', 'Ontario', 'CA'),
('ZSJ', 'Sandy Lake', 'Ontario', 'CA'),
('ZSN', 'South Indian Lake', 'Manitoba', 'CA'),
('ZST', 'Stewart', 'British-Columbia', 'CA'),
('YDV', 'Bloodvein River', 'Manitoba', 'CA'),
('ZTM', 'Shamattawa', 'Manitoba', 'CA'),
('ZUC', 'Ignace', 'Ontario', 'CA'),
('ZUM', 'Churchill Falls', 'Newfoundland-and-Labrador', 'CA'),
('ZWH', 'Lac Brochet', 'Manitoba', 'CA'),
('ZWL', 'Wollaston Lake', 'Saskatchewan', 'CA'),
('SEW', 'Siwa', 'Matruh', 'EG'),
('DBB', 'El Alamein', 'Matruh', 'EG'),
('AAC', 'El Arish', 'North-Sinai', 'EG'),
('ATZ', 'Assiut', 'Asyut', 'EG'),
('HBE', 'Alexandria', 'Alexandria', 'EG'),
('ABS', 'Abu Simbel', 'Aswan', 'EG'),
('CAI', 'Cairo', 'Cairo', 'EG'),
('CWE', 'El Cairo', 'Giza', 'EG'),
('HRG', 'Hurghada', 'Red-Sea', 'EG'),
('LXR', 'Luxor', 'Qena', 'EG'),
('RMF', 'Marsa Alam', 'Red-Sea', 'EG'),
('HMB', 'Sohag', 'New-Valley', 'EG'),
('MUH', 'Mersa Matruh', 'Matruh', 'EG'),
('PSD', 'Port Said', 'Port-Said', 'EG'),
('SSH', 'Sharm el-Sheikh', 'South-Sinai', 'EG'),
('ASW', 'Aswan', 'Aswan', 'EG'),
('SPX', 'Giza', 'Giza ', 'EG'),
('TCP', 'Taba', 'South-Sinai', 'EG'),
('AMK', 'Durango', 'Colorado', 'US'),
('BDX', 'Broadus', 'Montana', 'US'),
('FID', 'Fishers Island', 'New-York', 'US'),
('GCW', 'Peach Springs', 'Arizona', 'US'),
('RKC', 'Montague', 'California', 'US'),
('GNF', 'Quincy', 'California', 'US'),
('GTP', 'Grants Pass', 'Oregon', 'US'),
('GCD', 'Electric City', 'Washington', 'US'),
('FPY', 'Perry', 'Florida', 'US'),
('FMU', 'Florence', 'Oregon', 'US'),
('ATE', 'Antlers', 'Oklahoma', 'US'),
('AAF', 'Apalachicola', 'Florida', 'US'),
('ABE', 'Allentown', 'Pennsylvania', 'US'),
('ABI', 'Abilene', 'Texas', 'US'),
('ABQ', 'Albuquerque', 'New-Mexico', 'US'),
('ABR', 'Aberdeen', 'South-Dakota', 'US'),
('ABY', 'Albany', 'Georgia', 'US'),
('ACB', 'Bellaire', 'Michigan', 'US'),
('ACK', 'Nantucket', 'Massachusetts', 'US'),
('ACT', 'Waco', 'Texas', 'US'),
('ACV', 'Arcata/Eureka', 'California', 'US'),
('ACY', 'Atlantic City', 'New-Jersey', 'US'),
('ADG', 'Adrian', 'Michigan', 'US'),
('ADT', 'Ada', 'Oklahoma', 'US'),
('ADM', 'Ardmore', 'Oklahoma', 'US'),
('ADS', 'Dallas', 'Texas', 'US'),
('ADW', 'Camp Springs', 'Maryland', 'US'),
('AEL', 'Albert Lea', 'Minnesota', 'US'),
('AEX', 'Alexandria', 'Louisiana', 'US'),
('AFF', 'Colorado Springs', 'Colorado', 'US'),
('WSG', 'Washington', 'Pennsylvania', 'US'),
('AFN', 'Jaffrey', 'New-Hampshire', 'US'),
('AFO', 'Afton', 'Wyoming', 'US'),
('AFW', 'Fort Worth', 'Texas', 'US'),
('AGC', 'Pittsburgh', 'Pennsylvania', 'US'),
('AGO', 'Magnolia', 'Arkansas', 'US'),
('AGS', 'Augusta', 'Georgia', 'US'),
('AHC', 'Herlong', 'California', 'US'),
('AHH', 'Amery', 'Wisconsin', 'US'),
('AHN', 'Athens', 'Georgia', 'US'),
('AIA', 'Alliance', 'Nebraska', 'US'),
('AID', 'Anderson', 'Indiana', 'US'),
('AIK', 'Aiken', 'South-Carolina', 'US'),
('AIO', 'Atlantic', 'Iowa', 'US'),
('AIV', 'Aliceville', 'Alabama', 'US'),
('AIZ', 'Kaiser Lake Ozark', 'Missouri', 'US'),
('AKO', 'Akron', 'Colorado', 'US'),
('AKC', 'Akron', 'Ohio', 'US'),
('ALB', 'Albany', 'New-York', 'US'),
('ALI', 'Alice', 'Texas', 'US'),
('ALM', 'Alamogordo', 'New-Mexico', 'US'),
('ALN', 'Alton/St Louis', 'Illinois', 'US'),
('ALO', 'Waterloo', 'Iowa', 'US'),
('ALS', 'Alamosa', 'Colorado', 'US'),
('ALW', 'Walla Walla', 'Washington', 'US'),
('AMA', 'Amarillo', 'Texas', 'US'),
('AMN', 'Alma', 'Michigan', 'US'),
('AMW', 'Ames', 'Iowa', 'US'),
('ANB', 'Anniston', 'Alabama', 'US'),
('AND', 'Anderson', 'South-Carolina', 'US'),
('SLT', 'Salida', 'Colorado', 'US'),
('ANP', 'Annapolis', 'Maryland', 'US'),
('ANQ', 'Angola', 'Indiana', 'US'),
('ANW', 'Ainsworth', 'Nebraska', 'US'),
('ANY', 'Anthony', 'Kansas', 'US'),
('AOH', 'Lima', 'Ohio', 'US'),
('AOO', 'Altoona', 'Pennsylvania', 'US'),
('APA', 'Denver', 'Colorado', 'US'),
('APC', 'Napa', 'California', 'US'),
('APF', 'Naples', 'Florida', 'US'),
('APG', 'Aberdeen Proving Grounds(Aberdeen)', 'Maryland', 'US'),
('APH', 'Fort A. P. Hill', 'Virginia', 'US'),
('APN', 'Alpena', 'Michigan', 'US'),
('APT', 'Jasper', 'Tennessee', 'US'),
('APV', 'Apple Valley', 'California', 'US'),
('ARA', 'New Iberia', 'Louisiana', 'US'),
('ARB', 'Ann Arbor', 'Michigan', 'US'),
('ARG', 'Walnut Ridge', 'Arkansas', 'US'),
('WHT', 'Wharton', 'Texas', 'US'),
('AUZ', 'Chicago/Aurora', 'Illinois', 'US'),
('ART', 'Watertown', 'New-York', 'US'),
('ARV', 'Minocqua-Woodruff', 'Wisconsin', 'US'),
('BFT', 'Beaufort', 'South-Carolina', 'US'),
('ASE', 'Aspen', 'Colorado', 'US'),
('SPZ', 'Springdale', 'Arkansas', 'US'),
('ASH', 'Nashua', 'New-Hampshire', 'US'),
('ASL', 'Marshall', 'Texas', 'US'),
('ASN', 'Talladega', 'Alabama', 'US'),
('AST', 'Astoria', 'Oregon', 'US'),
('ASX', 'Ashland', 'Wisconsin', 'US'),
('ASY', 'Ashley', 'North-Dakota', 'US'),
('ATL', 'Atlanta', 'Georgia', 'US'),
('ATS', 'Artesia', 'New-Mexico', 'US'),
('ATW', 'Appleton', 'Wisconsin', 'US'),
('ATY', 'Watertown', 'South-Dakota', 'US'),
('AUG', 'Augusta', 'Maine', 'US'),
('AUM', 'Austin', 'Minnesota', 'US'),
('AUN', 'Auburn', 'California', 'US'),
('AUO', 'Auburn', 'Alabama', 'US'),
('AUS', 'Austin', 'Texas', 'US'),
('AUW', 'Wausau', 'Wisconsin', 'US'),
('AVL', 'Asheville', 'North-Carolina', 'US'),
('AVO', 'Avon Park', 'Florida', 'US'),
('AVP', 'Wilkes-Barre/Scranton', 'Pennsylvania', 'US'),
('AVW', 'Tucson', 'Arizona', 'US'),
('AVX', 'Avalon', 'California', 'US'),
('AWM', 'West Memphis', 'Arkansas', 'US'),
('AXG', 'Algona', 'Iowa', 'US'),
('AXN', 'Alexandria', 'Minnesota', 'US'),
('AXS', 'Altus', 'Oklahoma', 'US'),
('AXV', 'Wapakoneta', 'Ohio', 'US'),
('AXX', 'Angel Fire', 'New-Mexico', 'US'),
('AYS', 'Waycross', 'Georgia', 'US'),
('AZO', 'Kalamazoo', 'Michigan', 'US'),
('BAB', 'Marysville', 'California', 'US'),
('BAD', 'Bossier City', 'Louisiana', 'US'),
('BAF', 'Westfield/Springfield', 'Massachusetts', 'US'),
('CLU', 'Columbus', 'Indiana', 'US'),
('BAM', 'Battle Mountain', 'Nevada', 'US'),
('BBB', 'Benson', 'Minnesota', 'US'),
('BBD', 'Brady', 'Texas', 'US'),
('BKG', 'Branson', 'Missouri', 'US'),
('BTN', 'Bennettsville', 'South-Carolina', 'US'),
('BBW', 'Broken Bow', 'Nebraska', 'US'),
('BCB', 'Blacksburg', 'Virginia', 'US'),
('BCE', 'Bryce Canyon', 'Utah', 'US'),
('BCT', 'Boca Raton', 'Florida', 'US'),
('BDE', 'Baudette', 'Minnesota', 'US'),
('BDG', 'Blanding', 'Utah', 'US'),
('ILL', 'Willmar', 'Minnesota', 'US'),
('BDL', 'Hartford', 'Connecticut', 'US'),
('BDR', 'Bridgeport', 'Connecticut', 'US'),
('WBU', 'Boulder', 'Colorado', 'US'),
('BEC', 'Wichita', 'Kansas', 'US'),
('BED', 'Bedford', 'Massachusetts', 'US'),
('BEH', 'Benton Harbor', 'Michigan', 'US'),
('BFD', 'Bradford', 'Pennsylvania', 'US'),
('BFF', 'Scottsbluff', 'Nebraska', 'US'),
('BFI', 'Seattle', 'Washington', 'US'),
('BFL', 'Bakersfield', 'California', 'US'),
('BFM', 'Mobile', 'Alabama', 'US'),
('BFR', 'Bedford', 'Indiana', 'US'),
('BGD', 'Borger', 'Texas', 'US'),
('BGE', 'Bainbridge', 'Georgia', 'US'),
('BGM', 'Binghamton', 'New-York', 'US'),
('BGR', 'Bangor', 'Maine', 'US'),
('BHB', 'Bar Harbor', 'Maine', 'US'),
('BHM', 'Birmingham', 'Alabama', 'US'),
('BID', 'Block Island', 'Rhode-Island', 'US'),
('BIE', 'Beatrice', 'Nebraska', 'US'),
('BIF', 'Fort Bliss/El Paso', 'Texas', 'US'),
('BIH', 'Bishop', 'California', 'US'),
('BIL', 'Billings', 'Montana', 'US'),
('BIS', 'Bismarck', 'North-Dakota', 'US'),
('BIX', 'Biloxi', 'Mississippi', 'US'),
('BJC', 'Denver', 'Colorado', 'US'),
('BJI', 'Bemidji', 'Minnesota', 'US'),
('BJJ', 'Wooster', 'Ohio', 'US'),
('BKD', 'Breckenridge', 'Texas', 'US'),
('BKE', 'Baker City', 'Oregon', 'US'),
('BFK', 'Aurora', 'Colorado', 'US'),
('BKL', 'Cleveland', 'Ohio', 'US'),
('BKT', 'Blackstone', 'Virginia', 'US'),
('BKW', 'Beckley', 'West-Virginia', 'US'),
('BKX', 'Brookings', 'South-Dakota', 'US'),
('BLF', 'Bluefield', 'Illinois', 'US'),
('BLH', 'Blythe', 'California', 'US'),
('BLI', 'Bellingham', 'Washington', 'US'),
('BLM', 'Belmar/Farmingdale', 'New-Jersey', 'US'),
('BLU', 'Emigrant Gap', 'California', 'US'),
('BLV', 'Belleville', 'Illinois', 'US'),
('BMC', 'Brigham City', 'Utah', 'US'),
('BMG', 'Bloomington', 'Alabama', 'US'),
('BMI', 'Bloomington-Normal', 'Illinois', 'US'),
('BML', 'Berlin', 'New-Hampshire', 'US'),
('BMT', 'Beaumont', 'Texas', 'US'),
('BNA', 'Nashville', 'Tennessee', 'US'),
('BNG', 'Banning', 'California', 'US'),
('BNL', 'Barnwell', 'South-Carolina', 'US'),
('BNO', 'Burns', 'Oregon', 'US'),
('BNW', 'Boone', 'Iowa', 'US'),
('BOI', 'Boise', 'Idaho', 'US'),
('BOS', 'Boston', 'Massachusetts', 'US'),
('BOW', 'Bartow', 'Florida', 'US'),
('BGS', 'Big Spring', 'Texas', 'US'),
('BPI', 'Big Piney', 'Wyoming', 'US'),
('WMH', 'Mountain Home', 'Arkansas', 'US'),
('BWM', 'Bowman', 'North-Dakota', 'US'),
('BPT', 'Beaumont/Port Arthur', 'Texas', 'US'),
('BQK', 'Brunswick', 'Georgia', 'US'),
('BRD', 'Brainerd', 'Minnesota', 'US'),
('BRL', 'Burlington', 'Iowa', 'US'),
('BRO', 'Brownsville', 'Texas', 'US'),
('BRY', 'Bardstown', 'Kentucky', 'US'),
('BTF', 'Bountiful', 'Utah', 'US'),
('BTL', 'Battle Creek', 'Michigan', 'US'),
('BTM', 'Butte', 'Montana', 'US'),
('TTO', 'Britton', 'South-Dakota', 'US'),
('BTP', 'Butler', 'Pennsylvania', 'US'),
('BTR', 'Baton Rouge', 'Louisiana', 'US'),
('BTV', 'Burlington', 'Vermont', 'US'),
('BTY', 'Beatty', 'Nevada', 'US'),
('BUB', 'Burwell', 'Nebraska', 'US'),
('BUF', 'Buffalo', 'New-York', 'US'),
('BUM', 'Butler', 'Missouri', 'US'),
('BUR', 'Burbank', 'California', 'US'),
('BFP', 'Beaver Falls', 'Pennsylvania', 'US'),
('BVO', 'Bartlesville', 'Oklahoma', 'US'),
('MVW', 'Burlington/Mount Vernon', 'Washington', 'US'),
('BLD', 'Boulder City', 'Nevada', 'US'),
('BVX', 'Batesville', 'Arkansas', 'US'),
('BVY', 'Beverly', 'Massachusetts', 'US'),
('BWC', 'Brawley', 'California', 'US'),
('BWD', 'Brownwood', 'Texas', 'US'),
('BWG', 'Bowling Green', 'Kentucky', 'US'),
('BWI', 'Baltimore', 'Maryland', 'US'),
('WAH', 'Wahpeton', 'North-Dakota', 'US'),
('BXA', 'Bogalusa', 'Louisiana', 'US'),
('BXK', 'Buckeye', 'Arizona', 'US'),
('NHZ', 'Brunswick', 'Maine', 'US'),
('BYG', 'Buffalo', 'Wyoming', 'US'),
('BYH', 'Blytheville', 'Arkansas', 'US'),
('BYI', 'Burley', 'Idaho', 'US'),
('BYS', 'Fort Irwin/Barstow', 'California', 'US'),
('BBC', 'Bay City', 'Texas', 'US'),
('BZN', 'Bozeman', 'Montana', 'US'),
('CAD', 'Cadillac', 'Michigan', 'US'),
('CAE', 'Columbia', 'South-Carolina', 'US'),
('CIG', 'Craig', 'Colorado', 'US'),
('CAK', 'Akron', 'Ohio', 'US'),
('CAO', 'Clayton', 'New-Mexico', 'US'),
('CAR', 'Caribou', 'Maine', 'US'),
('CBE', 'Cumberland', 'West-Virginia', 'US'),
('CBF', 'Council Bluffs', 'Iowa', 'US'),
('CBK', 'Colby', 'Kansas', 'US'),
('CBM', 'Columbus', 'Mississippi', 'US'),
('CCB', 'Upland', 'California', 'US'),
('CCR', 'Concord', 'California', 'US'),
('CCY', 'Charles City', 'Iowa', 'US'),
('LLX', 'Lyndonville', 'Vermont', 'US'),
('CDC', 'Cedar City', 'Utah', 'US'),
('CDH', 'Camden', 'Arkansas', 'US'),
('CDK', 'Cedar Key', 'Florida', 'US'),
('CDN', 'Camden', 'New-York', 'US'),
('CDR', 'Chadron', 'Nebraska', 'US'),
('CDS', 'Childress', 'Texas', 'US'),
('CDW', 'Caldwell', 'New-Jersey', 'US'),
('CEA', 'Wichita', 'Kansas', 'US'),
('CEC', 'Crescent City', 'California', 'US'),
('CEF', 'Springfield/Chicopee', 'Massachusetts', 'US'),
('CEU', 'Clemson', 'South-Carolina', 'US'),
('CEV', 'Connersville', 'Indiana', 'US'),
('CEW', 'Crestview', 'Florida', 'US'),
('CEY', 'Murray', 'Kentucky', 'US'),
('CEZ', 'Cortez', 'Colorado', 'US'),
('CFD', 'Bryan', 'Texas', 'US'),
('TZC', 'Caro', 'Michigan', 'US'),
('CFT', 'Clifton/Morenci', 'Arizona', 'US'),
('CFV', 'Coffeyville', 'Kansas', 'US'),
('CGE', 'Cambridge', 'Maryland', 'US'),
('CGF', 'Cleveland', 'Ohio', 'US'),
('CGI', 'Cape Girardeau', 'Missouri', 'US'),
('CGS', 'College Park', 'Maryland', 'US'),
('CGZ', 'Casa Grande', 'Arizona', 'US'),
('CHA', 'Chattanooga', 'Tennessee', 'US'),
('CHK', 'Chickasha', 'Oklahoma', 'US'),
('CHO', 'Charlottesville', 'Virginia', 'US'),
('CHS', 'Charleston', 'South-Carolina', 'US'),
('CIC', 'Chico', 'California', 'US'),
('CID', 'Cedar Rapids', 'Iowa', 'US'),
('CIN', 'Carroll', 'Iowa', 'US'),
('CIR', 'Cairo', 'Illinois', 'US'),
('CIU', 'Sault Ste Marie', 'Michigan', 'US'),
('CKA', 'Cherokee', 'Oklahoma', 'US'),
('CKB', 'Clarksburg', 'West-Virginia', 'US'),
('GRM', 'Grand Marais', 'Minnesota', 'US'),
('CKM', 'Clarksdale', 'Mississippi', 'US'),
('CKN', 'Crookston', 'Minnesota', 'US'),
('CKV', 'Clarksville', 'Tennessee', 'US'),
('CLE', 'Cleveland', 'Ohio', 'US'),
('CLI', 'Clintonville', 'Wisconsin', 'US'),
('CLK', 'Clinton', 'Oklahoma', 'US'),
('CLL', 'College Station', 'Texas', 'US'),
('CLM', 'Port Angeles', 'Washington', 'US'),
('CLR', 'Calipatria', 'California', 'US'),
('CLS', 'Chehalis', 'Washington', 'US'),
('CLT', 'Charlotte', 'North-Carolina', 'US'),
('CLW', 'Clearwater', 'Florida', 'US'),
('CMH', 'Columbus', 'Ohio', 'US'),
('CMI', 'Champaign/Urbana', 'Illinois', 'US'),
('CMX', 'Hancock', 'Michigan', 'US'),
('CMY', 'Sparta', 'Wisconsin', 'US'),
('CNH', 'Claremont', 'New-Hampshire', 'US'),
('CNK', 'Concordia', 'Kansas', 'US'),
('CNM', 'Carlsbad', 'New-Mexico', 'US'),
('CNO', 'Chino', 'California', 'US'),
('CNU', 'Chanute', 'Kansas', 'US'),
('CNW', 'Waco', 'Texas', 'US'),
('CNY', 'Moab', 'Utah', 'US'),
('COD', 'Cody', 'Wyoming', 'US'),
('COE', 'Coeur d\'Alene', 'Idaho', 'US'),
('COF', 'Cocoa Beach', 'Florida', 'US'),
('COI', 'Merritt Island', 'Florida', 'US'),
('COM', 'Coleman', 'Texas', 'US'),
('CON', 'Concord', 'New-Hampshire', 'US'),
('COS', 'Colorado Springs', 'Colorado', 'US'),
('COT', 'Cotulla', 'Texas', 'US'),
('COU', 'Columbia', 'Missouri', 'US'),
('CPM', 'Compton', 'California', 'US'),
('CPR', 'Casper', 'Wyoming', 'US'),
('CPS', 'Cahokia/St Louis', 'Illinois', 'US'),
('HCW', 'Cheraw', 'South-Carolina', 'US'),
('CRE', 'North Myrtle Beach', 'South-Carolina', 'US'),
('CRG', 'Jacksonville', 'Florida', 'US'),
('CRO', 'Corcoran', 'California', 'US'),
('CRP', 'Corpus Christi', 'Texas', 'US'),
('CLD', 'Carlsbad', 'California', 'US'),
('CRS', 'Corsicana', 'Texas', 'US'),
('CRT', 'Crossett', 'Arkansas', 'US'),
('CRW', 'Charleston', 'West-Virginia', 'US'),
('CRX', 'Corinth', 'Mississippi', 'US'),
('CSG', 'Columbus', 'Georgia', 'US'),
('CSM', 'Clinton', 'Oklahoma', 'US'),
('CSQ', 'Creston', 'Iowa', 'US'),
('CSV', 'Crossville', 'Tennessee', 'US'),
('CTB', 'Cut Bank', 'Montana', 'US'),
('CTY', 'Cross City', 'Florida', 'US'),
('CTZ', 'Clinton', 'North-Carolina', 'US'),
('CUB', 'Columbia', 'South-Carolina', 'US'),
('CUH', 'Cushing', 'Oklahoma', 'US'),
('CVG', 'Hebron', 'Kentucky', 'US'),
('HLI', 'Hollister', 'California', 'US'),
('CKK', 'Ash Flat', 'Arkansas', 'US'),
('CVN', 'Clovis', 'New-Mexico', 'US'),
('CVO', 'Corvallis', 'Oregon', 'US'),
('CVS', 'Clovis', 'New-Mexico', 'US'),
('CWA', 'Mosinee', 'Wisconsin', 'US'),
('KIP', 'Wichita Falls', 'Texas', 'US'),
('CWF', 'Lake Charles', 'Louisiana', 'US'),
('CWI', 'Clinton', 'Arkansas', 'US'),
('CXL', 'Calexico', 'California', 'US'),
('CXO', 'Houston', 'Texas', 'US'),
('CSN', 'Carson City', 'Nevada', 'US'),
('HAR', 'Harrisburg', 'Pennsylvania', 'US'),
('CYS', 'Cheyenne', 'Wyoming', 'US'),
('CZT', 'Carrizo Springs', 'Texas', 'US'),
('DAA', 'Fort Belvoir', 'Virginia', 'US'),
('DAB', 'Daytona Beach', 'Florida', 'US'),
('DAG', 'Daggett', 'California', 'US'),
('DAL', 'Dallas', 'Texas', 'US'),
('DAN', 'Danville', 'Virginia', 'US'),
('DAY', 'Dayton', 'Ohio', 'US'),
('DBN', 'Dublin', 'Georgia', 'US'),
('DBQ', 'Dubuque', 'Iowa', 'US'),
('DCA', 'Washington', 'Virginia', 'US'),
('DCU', 'Decatur', 'Alabama', 'US'),
('DDC', 'Dodge City', 'Kansas', 'US'),
('DEC', 'Decatur', 'Illinois', 'US'),
('DEH', 'Decorah', 'Iowa', 'US'),
('DEN', 'Denver', 'Colorado', 'US'),
('DET', 'Detroit', 'Michigan', 'US'),
('DFI', 'Defiance', 'Ohio', 'US'),
('DFW', 'Dallas-Fort Worth', 'Texas', 'US'),
('DGL', 'Douglas', 'Arizona', 'US'),
('DGW', 'Douglas', 'Wyoming', 'US'),
('DHN', 'Dothan', 'Alabama', 'US'),
('DHT', 'Dalhart', 'Texas', 'US'),
('DIK', 'Dickinson', 'North-Dakota', 'US'),
('DKK', 'Dunkirk', 'New-York', 'US'),
('DLL', 'Dillon', 'South-Carolina', 'US'),
('DLF', 'Del Rio', 'Texas', 'US'),
('DLH', 'Duluth', 'Minnesota', 'US'),
('DLN', 'Dillon', 'Montana', 'US'),
('DLS', 'The Dalles', 'Washington', 'US'),
('DMA', 'Tucson', 'Arizona', 'US'),
('DMN', 'Deming', 'New-Mexico', 'US'),
('DMO', 'Sedalia', 'Missouri', 'US'),
('DNL', 'Augusta', 'Georgia', 'US'),
('DNN', 'Dalton', 'Georgia', 'US'),
('DNS', 'Denison', 'Iowa', 'US'),
('DNV', 'Danville', 'Illinois', 'US'),
('DOV', 'Dover', 'Delaware', 'US'),
('DPA', 'Chicago/West Chicago', 'Illinois', 'US'),
('DPG', 'Dugway Proving Ground', 'Utah', 'US'),
('DRA', 'Mercury', 'Nevada', 'US'),
('DRI', 'De Ridder', 'Louisiana', 'US'),
('DRE', 'Drummond Island', 'Michigan', 'US'),
('DRO', 'Durango', 'Colorado', 'US'),
('DRT', 'Del Rio', 'Texas', 'US'),
('DSM', 'Des Moines', 'Iowa', 'US'),
('DSV', 'Dansville', 'New-York', 'US'),
('DTA', 'Delta', 'Utah', 'US'),
('DTL', 'Detroit Lakes', 'Minnesota', 'US'),
('DTN', 'Shreveport', 'Louisiana', 'US'),
('DSI', 'Destin', 'Florida', 'US'),
('DTW', 'Detroit', 'Michigan', 'US'),
('DUA', 'Durant', 'Oklahoma', 'US'),
('DUC', 'Duncan', 'Oklahoma', 'US'),
('DUG', 'Douglas Bisbee', 'Arizona', 'US'),
('DUJ', 'Dubois', 'Pennsylvania', 'US'),
('DVL', 'Devils Lake', 'North-Dakota', 'US'),
('DVN', 'Davenport', 'Iowa', 'US'),
('NOT', 'Novato', 'California', 'US'),
('NSL', 'Slayton', 'Minnesota', 'US'),
('DVT', 'Phoenix', 'Arizona', 'US'),
('DWH', 'Houston', 'Texas', 'US'),
('DXR', 'Danbury', 'Connecticut', 'US'),
('DYL', 'Doylestown', 'Pennsylvania', 'US'),
('DYS', 'Abilene', 'Texas', 'US'),
('CCG', 'Crane', 'Texas', 'US'),
('BGQ', 'Big Lake', 'Texas', 'US'),
('BGT', 'Bagdad', 'Arizona', 'US'),
('EAN', 'Wheatland', 'Wyoming', 'US'),
('EAR', 'Kearney', 'Nebraska', 'US'),
('EAT', 'Wenatchee', 'Washington', 'US'),
('EAU', 'Eau Claire', 'Wisconsin', 'US'),
('EBS', 'Webster City', 'Iowa', 'US'),
('ECG', 'Elizabeth City', 'North-Carolina', 'US'),
('ECP', 'Panama City Beach', 'Florida', 'US'),
('ECS', 'Newcastle', 'Wyoming', 'US'),
('EDE', 'Edenton', 'North-Carolina', 'US'),
('ETS', 'Enterprise', 'Alabama', 'US'),
('EDW', 'Edwards', 'California', 'US'),
('EED', 'Needles', 'California', 'US'),
('EEN', 'Keene', 'New-Hampshire', 'US'),
('EFD', 'Houston', 'Connecticut', 'US'),
('EFK', 'Newport', 'Vermont', 'US'),
('EFW', 'Jefferson', 'Iowa', 'US'),
('EGE', 'Eagle', 'Colorado', 'US'),
('EGI', 'Crestview', 'Florida', 'US'),
('EGV', 'Eagle River', 'Wisconsin', 'US'),
('EKA', 'Eureka', 'California', 'US'),
('EKI', 'Elkhart', 'Indiana', 'US'),
('EKN', 'Elkins', 'West-Virginia', 'US'),
('EKO', 'Elko', 'Nevada', 'US'),
('EKX', 'Elizabethtown', 'Kentucky', 'US'),
('ELA', 'Eagle Lake', 'Texas', 'US'),
('ELD', 'El Dorado', 'Arkansas', 'US'),
('ELK', 'Elk City', 'Oklahoma', 'US'),
('ELM', 'Elmira/Corning', 'New-York', 'US'),
('ELN', 'Ellensburg', 'Washington', 'US'),
('LYU', 'Ely', 'Minnesota', 'US'),
('ELP', 'El Paso', 'Texas', 'US'),
('ELY', 'Ely', 'Nevada', 'US'),
('ELZ', 'Wellsville', 'New-York', 'US'),
('EMM', 'Kemmerer', 'Wyoming', 'US'),
('EMP', 'Emporia', 'Kansas', 'US'),
('EMT', 'El Monte', 'California', 'US'),
('END', 'Enid', 'Oklahoma', 'US'),
('ENL', 'Centralia', 'Illinois', 'US'),
('ENV', 'Wendover', 'Utah', 'US'),
('ENW', 'Kenosha', 'Wisconsin', 'US'),
('EOK', 'Keokuk', 'Iowa', 'US'),
('EOS', 'Neosho', 'Missouri', 'US'),
('EPH', 'Ephrata', 'Washington', 'US'),
('EDK', 'El Dorado', 'Kansas', 'US'),
('ERI', 'Erie', 'Pennsylvania', 'US'),
('ERR', 'Errol', 'New-Hampshire', 'US'),
('ERV', 'Kerrville', 'Texas', 'US'),
('ESC', 'Escanaba', 'Michigan', 'US'),
('ESF', 'Alexandria', 'Louisiana', 'US'),
('ESN', 'Easton', 'Maryland', 'US'),
('EST', 'Estherville', 'Iowa', 'US'),
('ESW', 'Easton', 'Washington', 'US'),
('ETB', 'West Bend', 'Wisconsin', 'US'),
('ETN', 'Eastland', 'Texas', 'US'),
('EUF', 'Eufaula', 'Alabama', 'US'),
('EUG', 'Eugene', 'Oregon', 'US'),
('EVM', 'Eveleth', 'Minnesota', 'US'),
('EVV', 'Evansville', 'Indiana', 'US'),
('EVW', 'Evanston', 'Wyoming', 'US'),
('EWB', 'New Bedford', 'Massachusetts', 'US'),
('EWK', 'Newton', 'Kansas', 'US'),
('EWN', 'New Bern', 'North-Carolina', 'US'),
('EWR', 'Newark', 'New-Jersey', 'US'),
('EYW', 'Key West', 'Florida', 'US'),
('FAF', 'Fort Eustis', 'Virginia', 'US'),
('FAM', 'Farmington', 'Missouri', 'US'),
('FAR', 'Fargo', 'North-Dakota', 'US'),
('FAT', 'Fresno', 'California', 'US'),
('FAY', 'Fayetteville', 'North-Carolina', 'US'),
('FBG', 'Fort Bragg', 'North-Carolina', 'US'),
('FBL', 'Faribault', 'Minnesota', 'US'),
('FBR', 'Fort Bridger', 'Wyoming', 'US'),
('FBY', 'Fairbury', 'Nebraska', 'US'),
('FCH', 'Fresno', 'California', 'US'),
('FCM', 'Minneapolis', 'Minnesota', 'US'),
('FCS', 'Fort Carson', 'Colorado', 'US'),
('FCY', 'Forrest City', 'Arkansas', 'US'),
('FDK', 'Frederick', 'Maryland', 'US'),
('FDR', 'Frederick', 'Oklahoma', 'US'),
('FDY', 'Findlay', 'Ohio', 'US'),
('FEP', 'Freeport', 'Illinois', 'US'),
('FET', 'Fremont', 'Nebraska', 'US'),
('FFA', 'Kill Devil Hills', 'North-Carolina', 'US'),
('FFL', 'Fairfield', 'Iowa', 'US'),
('FFM', 'Fergus Falls', 'Minnesota', 'US'),
('FFO', 'Dayton', 'Ohio', 'US'),
('FFT', 'Frankfort', 'Kentucky', 'US'),
('MSC', 'Mesa', 'Alabama', 'US'),
('FHB', 'Fernandina Beach', 'Florida', 'US'),
('FRD', 'Friday Harbor', 'Washington', 'US'),
('FHU', 'Fort Huachuca Sierra Vista', 'Arizona', 'US'),
('FKL', 'Franklin', 'Pennsylvania', 'US'),
('FKN', 'Franklin', 'Virginia', 'US'),
('FLD', 'Fond du Lac', 'Wisconsin', 'US'),
('FLG', 'Flagstaff', 'Arizona', 'US'),
('FLL', 'Fort Lauderdale', 'Florida', 'US'),
('FLO', 'Florence', 'South-Carolina', 'US'),
('FLP', 'Flippin', 'Arkansas', 'US'),
('FLV', 'Fort Leavenworth', 'Kansas', 'US'),
('FLX', 'Fallon', 'Nevada', 'US'),
('FME', 'Fort Meade(Odenton)', 'Maryland', 'US'),
('FMH', 'Falmouth', 'Massachusetts', 'US'),
('FMN', 'Farmington', 'New-Mexico', 'US'),
('FMY', 'Fort Myers', 'Florida', 'US'),
('FNL', 'Fort Collins/Loveland', 'Colorado', 'US'),
('FNT', 'Flint', 'Michigan', 'US'),
('FOD', 'Fort Dodge', 'Iowa', 'US'),
('FOE', 'Topeka', 'Kansas', 'US'),
('FOK', 'Westhampton Beach', 'New-York', 'US'),
('FIL', 'Fillmore', 'Utah', 'US'),
('FPR', 'Fort Pierce', 'Florida', 'US'),
('FRG', 'Farmingdale', 'New-York', 'US'),
('FRH', 'French Lick', 'Indiana', 'US'),
('FRI', 'Fort Riley(Junction City)', 'Kansas', 'US'),
('FRM', 'Fairmont', 'Minnesota', 'US'),
('FRR', 'Front Royal', 'Virginia', 'US'),
('FSD', 'Sioux Falls', 'South-Dakota', 'US'),
('FSI', 'Fort Sill', 'Oklahoma', 'US'),
('FSK', 'Fort Scott', 'Kansas', 'US'),
('FSM', 'Fort Smith', 'Arkansas', 'US'),
('FST', 'Fort Stockton', 'Texas', 'US'),
('FSU', 'Fort Sumner', 'New-Mexico', 'US'),
('FMS', 'Fort Madison', 'Iowa', 'US'),
('FTK', 'Fort Knox', 'Kentucky', 'US'),
('FTW', 'Fort Worth', 'Texas', 'US'),
('FTY', 'Atlanta', 'Georgia', 'US'),
('FUL', 'Fullerton', 'California', 'US'),
('WFK', 'Frenchville', 'Maine', 'US'),
('FWA', 'Fort Wayne', 'Indiana', 'US'),
('FXE', 'Fort Lauderdale', 'Florida', 'US'),
('FXY', 'Forest City', 'Iowa', 'US'),
('FYM', 'Fayetteville', 'Tennessee', 'US'),
('FYV', 'Fayetteville', 'Arkansas', 'US'),
('GAB', 'Gabbs', 'Nevada', 'US'),
('GAD', 'Gadsden', 'Alabama', 'US'),
('GAG', 'Gage', 'Oklahoma', 'US'),
('GAI', 'Gaithersburg', 'Maryland', 'US'),
('GBD', 'Great Bend', 'Kansas', 'US'),
('GBG', 'Galesburg', 'Illinois', 'US'),
('GBR', 'Great Barrington', 'Massachusetts', 'US'),
('GCC', 'Gillette', 'Wyoming', 'US'),
('JDA', 'John Day', 'Oregon', 'US'),
('GCK', 'Garden City', 'Kansas', 'US'),
('GCN', 'Grand Canyon', 'Arizona', 'US'),
('GCY', 'Greeneville', 'Tennessee', 'US'),
('GDM', 'Gardner', 'Massachusetts', 'US'),
('GDV', 'Glendive', 'Montana', 'US'),
('GDW', 'Gladwin', 'Michigan', 'US'),
('GDY', 'Grundy', 'Virginia', 'US'),
('GED', 'Georgetown', 'Delaware', 'US'),
('GEG', 'Spokane', 'Washington', 'US'),
('GEY', 'Greybull', 'Wyoming', 'US'),
('GFK', 'Grand Forks', 'North-Dakota', 'US'),
('GFL', 'Glens Falls', 'New-York', 'US'),
('GGE', 'Georgetown', 'South-Carolina', 'US'),
('GGG', 'Longview', 'Texas', 'US'),
('GGW', 'Glasgow', 'Montana', 'US'),
('GHM', 'Centerville', 'Tennessee', 'US'),
('IDH', 'Grangeville', 'Idaho', 'US'),
('GIF', 'Winter Haven', 'Florida', 'US'),
('GJT', 'Grand Junction', 'Colorado', 'US'),
('MEJ', 'Meadville', 'Pennsylvania', 'US'),
('GKT', 'Sevierville', 'Tennessee', 'US'),
('GLD', 'Goodland', 'Kansas', 'US'),
('GLE', 'Gainesville', 'Texas', 'US'),
('GLH', 'Greenville', 'Mississippi', 'US'),
('GLR', 'Gaylord', 'Michigan', 'US'),
('GLS', 'Galveston', 'Texas', 'US'),
('GLW', 'Glasgow', 'Kentucky', 'US'),
('GMU', 'Greenville', 'South-Carolina', 'US'),
('GNG', 'Gooding', 'Idaho', 'US'),
('GNT', 'Grants', 'New-Mexico', 'US'),
('GNV', 'Gainesville', 'Florida', 'US'),
('GOK', 'Guthrie', 'Oklahoma', 'US'),
('GON', 'Groton (New London)', 'Connecticut', 'US'),
('FCA', 'Kalispell', 'Montana', 'US'),
('GPT', 'Gulfport', 'Mississippi', 'US'),
('GPZ', 'Grand Rapids', 'Minnesota', 'US'),
('GQQ', 'Galion', 'Ohio', 'US'),
('GRB', 'Green Bay', 'Wisconsin', 'US'),
('GRD', 'Greenwood', 'South-Carolina', 'US'),
('GRE', 'Greenville', 'Illinois', 'US'),
('GRF', 'Fort Lewis/Tacoma', 'Washington', 'US'),
('GRI', 'Grand Island', 'Nebraska', 'US'),
('GRK', 'Fort Hood/Killeen', 'Texas', 'US'),
('GRN', 'Gordon', 'Nebraska', 'US'),
('GRR', 'Grand Rapids', 'Michigan', 'US'),
('GSB', 'Goldsboro', 'North-Carolina', 'US'),
('GSH', 'Goshen', 'Indiana', 'US'),
('GSO', 'Greensboro', 'North-Carolina', 'US'),
('GSP', 'Greenville', 'South-Carolina', 'US'),
('GTB', 'Fort Drum', 'New-York', 'US'),
('GTF', 'Great Falls', 'Montana', 'US'),
('GTG', 'Grantsburg', 'Wisconsin', 'US'),
('GTR', 'Columbus/W Point/Starkville', 'Mississippi', 'US'),
('GUC', 'Gunnison', 'Colorado', 'US'),
('GUP', 'Gallup', 'New-Mexico', 'US'),
('GUS', 'Peru', 'Indiana', 'US'),
('GUY', 'Guymon', 'Oklahoma', 'US'),
('GVL', 'Gainesville', 'Georgia', 'US'),
('GVT', 'Greenville', 'California', 'US'),
('GWO', 'Greenwood', 'Mississippi', 'US'),
('GWS', 'Glenwood Springs', 'Colorado', 'US'),
('GXY', 'Greeley', 'Colorado', 'US'),
('GDC', 'Greenville', 'South-Carolina', 'US'),
('PNX', 'Sherman/Denison', 'Texas', 'US'),
('GYR', 'Goodyear', 'Arizona', 'US'),
('GYY', 'Gary', 'Indiana', 'US'),
('HAB', 'Hamilton', 'Alabama', 'US'),
('HAF', 'Half Moon Bay', 'California', 'US'),
('HAI', 'Three Rivers', 'Michigan', 'US'),
('HAO', 'Hamilton', 'Ohio', 'US'),
('HBG', 'Hattiesburg', 'Mississippi', 'US'),
('HBR', 'Hobart', 'Oklahoma', 'US'),
('HDE', 'Holdrege', 'Nebraska', 'US'),
('HDN', 'Hayden', 'Colorado', 'US'),
('HEE', 'Helena/West Helena', 'Arkansas', 'US'),
('MNZ', 'Manassas', 'Virginia', 'US'),
('HEZ', 'Natchez', 'Mississippi', 'US'),
('HFD', 'Hartford', 'Connecticut', 'US'),
('HFF', 'Camp Mackall', 'North-Carolina', 'US'),
('HGR', 'Hagerstown', 'Maryland', 'US'),
('HHR', 'Hawthorne', 'California', 'US'),
('HUJ', 'Hugo', 'Oklahoma', 'US'),
('HIB', 'Hibbing', 'Minnesota', 'US'),
('HIE', 'Whitefield', 'New-Hampshire', 'US'),
('HIF', 'Ogden', 'Utah', 'US'),
('HII', 'Lake Havasu City', 'Arizona', 'US'),
('HIO', 'Portland', 'Oregon', 'US'),
('HKA', 'Blytheville', 'Arkansas', 'US'),
('HKS', 'Jackson', 'Mississippi', 'US'),
('HKY', 'Hickory', 'North-Carolina', 'US'),
('HLB', 'Batesville', 'Indiana', 'US'),
('HLC', 'Hill City', 'Kansas', 'US'),
('HLG', 'Wheeling', 'West-Virginia', 'US'),
('HLM', 'Holland', 'Michigan', 'US'),
('HLN', 'Helena', 'Montana', 'US'),
('HLR', 'Fort Hood(Killeen)', 'Texas', 'US'),
('HMN', 'Alamogordo', 'New-Mexico', 'US'),
('HMT', 'Hemet', 'California', 'US'),
('HNB', 'Huntingburg', 'Indiana', 'US'),
('HSH', 'Las Vegas', 'Nevada', 'US'),
('HOB', 'Hobbs', 'New-Mexico', 'US'),
('HON', 'Huron', 'South-Dakota', 'US'),
('HOP', 'Fort Campbell/Hopkinsville', 'Kentucky', 'US'),
('HOT', 'Hot Springs', 'Iowa', 'US'),
('HOU', 'Houston', 'Texas', 'US'),
('HPN', 'White Plains', 'New-York', 'US'),
('HPT', 'Hampton', 'Iowa', 'US'),
('HPY', 'Baytown', 'Texas', 'US'),
('HQM', 'Hoquiam', 'Washington', 'US'),
('HES', 'Hermiston', 'Oregon', 'US'),
('HRL', 'Harlingen', 'Texas', 'US'),
('HRO', 'Harrison', 'Arkansas', 'US'),
('HSB', 'Harrisburg', 'Illinois', 'US'),
('HNC', 'Hatteras', 'North-Carolina', 'US'),
('HSI', 'Hastings', 'Nebraska', 'US'),
('HSP', 'Hot Springs', 'Virginia', 'US'),
('HST', 'Homestead', 'Florida', 'US'),
('HSV', 'Huntsville', 'Alabama', 'US'),
('HTH', 'Hawthorne', 'Nevada', 'US'),
('HTL', 'Houghton Lake', 'Michigan', 'US'),
('HTO', 'East Hampton', 'New-York', 'US'),
('HTS', 'Huntington', 'West-Virginia', 'US'),
('HTW', 'Chesapeake/Huntington Wva', 'Ohio', 'US'),
('HUA', 'Redstone Arsnl Huntsville', 'Alabama', 'US'),
('HUF', 'Terre Haute', 'Indiana', 'US'),
('HUL', 'Houlton', 'Maine', 'US'),
('HUM', 'Houma', 'Louisiana', 'US'),
('HUT', 'Hutchinson', 'Kansas', 'US'),
('HVE', 'Hanksville', 'Utah', 'US'),
('HVN', 'New Haven', 'Connecticut', 'US'),
('HVR', 'Havre', 'Montana', 'US'),
('HVS', 'Hartsville', 'South-Carolina', 'US'),
('HWD', 'Hayward', 'California', 'US'),
('HWO', 'Hollywood', 'Florida', 'US'),
('WSH', 'Shirley', 'New-York', 'US'),
('HHH', 'Hilton Head Island', 'South-Carolina', 'US'),
('HYA', 'Hyannis', 'Massachusetts', 'US'),
('HYR', 'Hayward', 'Wisconsin', 'US'),
('HYS', 'Hays', 'Kansas', 'US'),
('HZL', 'Hazleton', 'Pennsylvania', 'US'),
('JFN', 'Ashtabula', 'Ohio', 'US'),
('IAB', 'Wichita', 'Kansas', 'US'),
('IAD', 'Dulles', 'Virginia', 'US'),
('IAG', 'Niagara Falls', 'New-York', 'US'),
('IAH', 'Houston', 'Texas', 'US'),
('ICL', 'Clarinda', 'Iowa', 'US'),
('ICT', 'Wichita', 'Kansas', 'US'),
('IDA', 'Idaho Falls', 'Idaho', 'US'),
('IDG', 'Ida Grove', 'Iowa', 'US'),
('IDI', 'Indiana', 'Pennsylvania', 'US'),
('IDP', 'Independence', 'Kansas', 'US'),
('XPR', 'Pine Ridge', 'South-Dakota', 'US'),
('IFA', 'Iowa Falls', 'Iowa', 'US'),
('IFP', 'Bullhead City', 'Arizona', 'US'),
('IGM', 'Kingman', 'Arizona', 'US'),
('IJX', 'Jacksonville', 'Illinois', 'US'),
('IKK', 'Kankakee', 'Illinois', 'US'),
('ILE', 'Killeen', 'Texas', 'US'),
('ILG', 'Wilmington', 'Delaware', 'US'),
('ILM', 'Wilmington', 'North-Carolina', 'US'),
('ILN', 'Wilmington', 'Ohio', 'US'),
('IML', 'Imperial', 'Nebraska', 'US'),
('IMM', 'Immokalee', 'Florida', 'US'),
('MDN', 'Madison', 'Indiana', 'US'),
('IMT', 'Iron Mountain Kingsford', 'Michigan', 'US'),
('IND', 'Indianapolis', 'Indiana', 'US'),
('INK', 'Wink', 'Texas', 'US'),
('INL', 'International Falls', 'Minnesota', 'US'),
('INS', 'Indian Springs', 'Nevada', 'US'),
('INT', 'Winston Salem', 'North-Carolina', 'US'),
('INW', 'Winslow', 'Arizona', 'US'),
('IOW', 'Iowa City', 'Iowa', 'US'),
('IPL', 'Imperial', 'California', 'US'),
('IPT', 'Williamsport', 'Pennsylvania', 'US'),
('IRK', 'Kirksville', 'Missouri', 'US'),
('IRS', 'Sturgis', 'Michigan', 'US'),
('ISM', 'Orlando', 'Florida', 'US'),
('ISN', 'Williston', 'North-Dakota', 'US'),
('ISO', 'Kinston', 'North-Carolina', 'US'),
('ISP', 'Islip', 'New-York', 'US'),
('ISQ', 'Manistique', 'Michigan', 'US'),
('ISW', 'Wisconsin Rapids', 'Wisconsin', 'US'),
('ITH', 'Ithaca', 'New-York', 'US'),
('AZA', 'Phoenix', 'Arizona', 'US'),
('IWD', 'Ironwood', 'Michigan', 'US'),
('ISS', 'Wiscasset', 'Maine', 'US'),
('IWS', 'Houston', 'Texas', 'US'),
('JCI', 'Olathe', 'Kansas', 'US'),
('IYK', 'Inyokern', 'California', 'US'),
('SQA', 'Santa Ynez', 'California', 'US'),
('FRY', 'Fryeburg', 'Maine', 'US'),
('JAC', 'Jackson', 'Wyoming', 'US'),
('JAN', 'Jackson', 'Mississippi', 'US'),
('JAS', 'Jasper', 'Texas', 'US'),
('JAX', 'Jacksonville', 'Florida', 'US'),
('JBR', 'Jonesboro', 'Arkansas', 'US'),
('JCT', 'Junction', 'Texas', 'US'),
('JDN', 'Jordan', 'Montana', 'US'),
('JEF', 'Jefferson City', 'Missouri', 'US'),
('JFK', 'New York', 'New-York', 'US'),
('JHW', 'Jamestown', 'New-York', 'US'),
('GUF', 'Gulf Shores', 'Alabama', 'US'),
('JLN', 'Joplin', 'Missouri', 'US'),
('JMS', 'Jamestown', 'North-Dakota', 'US'),
('JOT', 'Joliet', 'Illinois', 'US'),
('USA', 'Concord', 'North-Carolina', 'US'),
('JKV', 'Jacksonville', 'Texas', 'US'),
('JST', 'Johnstown', 'Pennsylvania', 'US'),
('JVL', 'Janesville', 'Wisconsin', 'US'),
('JXN', 'Jackson', 'Michigan', 'US'),
('KIC', 'King City', 'California', 'US'),
('KLS', 'Kelso', 'Washington', 'US'),
('KNB', 'Kanab', 'Utah', 'US'),
('BXS', 'Borrego Springs', 'California', 'US'),
('LAA', 'Lamar', 'Colorado', 'US'),
('LAF', 'Lafayette', 'Indiana', 'US'),
('LAL', 'Lakeland', 'Florida', 'US'),
('LAM', 'Los Alamos', 'New-Mexico', 'US'),
('LAN', 'Lansing', 'Michigan', 'US'),
('LAR', 'Laramie', 'Wyoming', 'US'),
('LAS', 'Las Vegas', 'Nevada', 'US'),
('LAW', 'Lawton', 'Oklahoma', 'US'),
('LAX', 'Los Angeles', 'California', 'US'),
('LBB', 'Lubbock', 'Texas', 'US'),
('LBE', 'Latrobe', 'Pennsylvania', 'US'),
('LBF', 'North Platte', 'Nebraska', 'US'),
('LBL', 'Liberal', 'Kansas', 'US'),
('LBT', 'Lumberton', 'North-Carolina', 'US'),
('LJN', 'Angleton/Lake Jackson', 'Texas', 'US'),
('LCH', 'Lake Charles', 'Louisiana', 'US'),
('LCI', 'Laconia', 'New-Hampshire', 'US'),
('LCK', 'Columbus', 'Ohio', 'US'),
('LCQ', 'Lake City', 'Florida', 'US'),
('LDJ', 'Linden', 'New-Jersey', 'US'),
('LDM', 'Ludington', 'Michigan', 'US'),
('LEB', 'Lebanon', 'New-Hampshire', 'US'),
('LEE', 'Leesburg', 'Florida', 'US'),
('LEM', 'Lemmon', 'South-Dakota', 'US'),
('LEW', 'Auburn/Lewiston', 'Maine', 'US'),
('LEX', 'Lexington', 'Kentucky', 'US'),
('LFI', 'Hampton', 'Virginia', 'US'),
('LFK', 'Lufkin', 'Texas', 'US'),
('LFT', 'Lafayette', 'Louisiana', 'US'),
('LGA', 'New York', 'New-York', 'US'),
('LGB', 'Long Beach', 'California', 'US'),
('LGC', 'Lagrange', 'Georgia', 'US'),
('LGD', 'La Grande', 'Oregon', 'US'),
('LGF', 'Yuma Proving Ground(Yuma)', 'Arizona', 'US'),
('LGU', 'Logan', 'Utah', 'US'),
('LHV', 'Lock Haven', 'Pennsylvania', 'US'),
('LIY', 'Fort Stewart(Hinesville)', 'Georgia', 'US'),
('LFN', 'Louisburg', 'North-Carolina', 'US'),
('LIC', 'Limon', 'Colorado', 'US'),
('LIT', 'Little Rock', 'Arkansas', 'US'),
('LKP', 'Lake Placid', 'New-York', 'US'),
('LOW', 'Louisa', 'Virginia', 'US'),
('LKV', 'Lakeview', 'Colorado', 'US'),
('CHL', 'Challis', 'Idaho', 'US'),
('LMS', 'Louisville', 'Mississippi', 'US'),
('LMT', 'Klamath Falls', 'Oregon', 'US'),
('LNA', 'West Palm Beach', 'Florida', 'US'),
('LND', 'Lander', 'Wyoming', 'US'),
('LNK', 'Lincoln', 'Montana', 'US'),
('LNN', 'Willoughby', 'Ohio', 'US'),
('LNP', 'Wise', 'Virginia', 'US'),
('LNR', 'Lone Rock', 'Wisconsin', 'US'),
('LNS', 'Lancaster', 'Pennsylvania', 'US'),
('LOL', 'Lovelock', 'Nevada', 'US'),
('BBX', 'Philadelphia', 'Florida', 'US'),
('LOT', 'Chicago/Romeoville', 'Illinois', 'US'),
('LOU', 'Louisville', 'Kentucky', 'US'),
('LOZ', 'London', 'Kentucky', 'US'),
('LPC', 'Lompoc', 'California', 'US'),
('LQK', 'Pickens', 'South-Carolina', 'US'),
('LRD', 'Laredo', 'Texas', 'US'),
('LRF', 'Jacksonville', 'Arkansas', 'US'),
('LRJ', 'Le Mars', 'Iowa', 'US'),
('LRU', 'Las Cruces', 'New-Mexico', 'US'),
('LSB', 'Lordsburg', 'New-Mexico', 'US'),
('LSE', 'La Crosse', 'Wisconsin', 'US'),
('LSF', 'Fort Benning(Columbus)', 'Georgia', 'US'),
('LSK', 'Lusk', 'Wyoming', 'US'),
('LSN', 'Los Banos', 'California', 'US'),
('LSV', 'Las Vegas', 'Nevada', 'US'),
('LTS', 'Altus', 'Oklahoma', 'US'),
('LUF', 'Glendale', 'Arizona', 'US'),
('LUK', 'Cincinnati', 'Ohio', 'US'),
('LUL', 'Laurel', 'Mississippi', 'US'),
('LVK', 'Livermore', 'California', 'US'),
('LVL', 'Lawrenceville', 'Virginia', 'US'),
('LVM', 'Livingston', 'Montana', 'US'),
('LVS', 'Las Vegas', 'New-Mexico', 'US'),
('LWB', 'Lewisburg', 'West-Virginia', 'US'),
('LWC', 'Lawrence', 'Kansas', 'US'),
('LWL', 'Wells', 'Nevada', 'US'),
('LWM', 'Lawrence', 'Massachusetts', 'US'),
('LWS', 'Lewiston', 'Idaho', 'US'),
('LWT', 'Lewistown', 'Montana', 'US'),
('LWV', 'Lawrenceville', 'Illinois', 'US'),
('LXN', 'Lexington', 'Nebraska', 'US'),
('LXV', 'Leadville', 'Colorado', 'US'),
('LYH', 'Lynchburg', 'Virginia', 'US'),
('LYO', 'Lyons', 'Kansas', 'US'),
('LZU', 'Lawrenceville', 'Georgia', 'US'),
('MAC', 'Macon', 'Georgia', 'US'),
('MAE', 'Madera', 'California', 'US'),
('MAF', 'Midland', 'Texas', 'US'),
('MAW', 'Malden', 'Missouri', 'US'),
('MBG', 'Mobridge', 'South-Dakota', 'US'),
('MBL', 'Manistee', 'Michigan', 'US'),
('DXE', 'Madison', 'Mississippi', 'US'),
('MBS', 'Saginaw', 'Michigan', 'US'),
('MBY', 'Moberly', 'Missouri', 'US'),
('MCB', 'Mc Comb', 'Mississippi', 'US'),
('MCC', 'Sacramento', 'California', 'US'),
('MCD', 'Mackinac Island', 'Michigan', 'US'),
('MCE', 'Merced', 'California', 'US'),
('MCF', 'Tampa', 'Florida', 'US'),
('MCI', 'Kansas City', 'Missouri', 'US'),
('MCK', 'Mc Cook', 'Nebraska', 'US'),
('MCN', 'Macon', 'Georgia', 'US'),
('MCO', 'Orlando', 'Florida', 'US'),
('MCW', 'Mason City', 'Iowa', 'US'),
('MDD', 'Midland', 'Texas', 'US'),
('MDH', 'Carbondale/Murphysboro', 'Illinois', 'US'),
('XMD', 'Madison', 'South-Dakota', 'US'),
('MDT', 'Harrisburg', 'Pennsylvania', 'US'),
('MDW', 'Chicago', 'Illinois', 'US'),
('MDF', 'Medford', 'Wisconsin', 'US'),
('MXE', 'Maxton', 'North-Carolina', 'US'),
('MEI', 'Meridian', 'Mississippi', 'US'),
('MEM', 'Memphis', 'Tennessee', 'US'),
('MER', 'Merced', 'California', 'US'),
('MEV', 'Minden', 'Nevada', 'US'),
('MFD', 'Mansfield', 'Ohio', 'US'),
('MFE', 'Mc Allen', 'Texas', 'US'),
('MFI', 'Marshfield', 'Wisconsin', 'US'),
('MFR', 'Medford', 'Oregon', 'US'),
('MFV', 'Melfa', 'Virginia', 'US'),
('MGC', 'Michigan City', 'Indiana', 'US'),
('MGE', 'Marietta', 'Georgia', 'US'),
('MGJ', 'Montgomery', 'New-York', 'US'),
('MGM', 'Montgomery', 'Alabama', 'US'),
('MGR', 'Moultrie', 'Georgia', 'US'),
('MGW', 'Morgantown', 'West-Virginia', 'US'),
('MGY', 'Dayton', 'Ohio', 'US'),
('MHE', 'Mitchell', 'South-Dakota', 'US'),
('MHK', 'Manhattan', 'Kansas', 'US'),
('MHL', 'Marshall', 'Missouri', 'US'),
('MHR', 'Sacramento', 'California', 'US'),
('MHT', 'Manchester', 'New-Hampshire', 'US'),
('MHV', 'Mojave', 'California', 'US'),
('MIA', 'Miami', 'Florida', 'US'),
('MIB', 'Minot', 'North-Dakota', 'US'),
('MIC', 'Minneapolis', 'Minnesota', 'US'),
('MIE', 'Muncie', 'Indiana', 'US'),
('MIO', 'Miami', 'Oklahoma', 'US'),
('MIT', 'Shafter', 'California', 'US'),
('MIV', 'Millville', 'New-Jersey', 'US'),
('MIW', 'Marshalltown', 'Iowa', 'US'),
('MJQ', 'Jackson', 'Minnesota', 'US'),
('MJX', 'Toms River', 'New-Jersey', 'US'),
('MKC', 'Kansas City', 'Missouri', 'US'),
('MKE', 'Milwaukee', 'Wisconsin', 'US'),
('MKG', 'Muskegon', 'Michigan', 'US'),
('MKL', 'Jackson', 'Tennessee', 'US'),
('MKO', 'Muskogee', 'Florida', 'US'),
('MKT', 'Mankato', 'Minnesota', 'US'),
('MRK', 'Marco Island', 'Florida', 'US'),
('MLB', 'Melbourne', 'Florida', 'US'),
('MLC', 'Mc Alester', 'Oklahoma', 'US'),
('MLD', 'Malad City', 'Idaho', 'US'),
('MIQ', 'Omaha', 'Nebraska', 'US'),
('MLF', 'Milford', 'Utah', 'US'),
('MLI', 'Moline', 'Illinois', 'US'),
('MLJ', 'Milledgeville', 'Georgia', 'US'),
('MLS', 'Miles City', 'Montana', 'US'),
('MLT', 'Millinocket', 'Maine', 'US'),
('MLU', 'Monroe', 'Louisiana', 'US'),
('MMH', 'Mammoth Lakes', 'California', 'US'),
('MMI', 'Athens', 'Tennessee', 'US'),
('MML', 'Marshall', 'Minnesota', 'US'),
('MMS', 'Marks', 'Mississippi', 'US'),
('MMT', 'Eastover', 'South-Carolina', 'US'),
('MMU', 'Morristown', 'New-Jersey', 'US'),
('MNM', 'Menominee', 'Michigan', 'US'),
('MNN', 'Marion', 'Ohio', 'US'),
('MOB', 'Mobile', 'Alabama', 'US'),
('MOD', 'Modesto', 'California', 'US'),
('MOP', 'Mount Pleasant', 'Michigan', 'US'),
('MOR', 'Morristown', 'Tennessee', 'US'),
('MOT', 'Minot', 'North-Dakota', 'US'),
('MOX', 'Morris', 'Minnesota', 'US'),
('RMY', 'Mariposa', 'California', 'US'),
('MPJ', 'Morrilton', 'Arkansas', 'US'),
('MPO', 'Mount Pocono', 'Pennsylvania', 'US'),
('MPR', 'Mc Pherson', 'Kansas', 'US'),
('MPV', 'Barre/Montpelier', 'Vermont', 'US'),
('MPZ', 'Mount Pleasant', 'Iowa', 'US'),
('MQB', 'Macomb', 'Illinois', 'US'),
('MEO', 'Manteo', 'North-Carolina', 'US'),
('CTH', 'Coatesville', 'Pennsylvania', 'US'),
('MQW', 'Mc Rae', 'Georgia', 'US'),
('MQY', 'Smyrna', 'Delaware', 'US'),
('MRB', 'Martinsburg', 'West-Virginia', 'US'),
('MRC', 'Columbia/Mount Pleasant', 'Tennessee', 'US'),
('MRF', 'Marfa', 'Texas', 'US'),
('MRN', 'Morganton', 'North-Carolina', 'US'),
('MRY', 'Monterey', 'California', 'US'),
('MSL', 'Muscle Shoals', 'Alabama', 'US'),
('MSN', 'Madison', 'Wisconsin', 'US'),
('MSO', 'Missoula', 'Montana', 'US'),
('MSP', 'Minneapolis', 'Minnesota', 'US'),
('MSS', 'Massena', 'New-York', 'US'),
('MSV', 'Monticello', 'New-York', 'US'),
('MSY', 'New Orleans', 'Louisiana', 'US'),
('MTC', 'Mount Clemens', 'Michigan', 'US'),
('MTH', 'Marathon', 'Florida', 'US'),
('MTJ', 'Montrose', 'Colorado', 'US'),
('MTN', 'Baltimore', 'Maryland', 'US'),
('MTO', 'Mattoon/Charleston', 'Illinois', 'US'),
('MTP', 'Montauk', 'New-York', 'US'),
('MTW', 'Manitowoc', 'Wisconsin', 'US'),
('MUI', 'Fort Indiantown Gap(Annville)', 'Pennsylvania', 'US'),
('MUL', 'Moultrie', 'Georgia', 'US'),
('MUO', 'Mountain Home', 'Idaho', 'US'),
('MUT', 'Muscatine', 'Iowa', 'US'),
('MVC', 'Monroeville', 'Alabama', 'US'),
('MVE', 'Montevideo', 'Minnesota', 'US'),
('MVL', 'Morrisville', 'Vermont', 'US'),
('MVN', 'Mount Vernon', 'Illinois', 'US'),
('MVY', 'Martha\'s Vineyard', 'Massachusetts', 'US'),
('MWA', 'Marion', 'Illinois', 'US'),
('MWC', 'Milwaukee', 'Wisconsin', 'US'),
('MWH', 'Moses Lake', 'Washington', 'US'),
('MWL', 'Mineral Wells', 'Texas', 'US'),
('MWM', 'Windom', 'Minnesota', 'US'),
('MWO', 'Middletown', 'Ohio', 'US'),
('MXA', 'Manila', 'Arkansas', 'US'),
('MXF', 'Montgomery', 'Alabama', 'US'),
('MXO', 'Monticello', 'Iowa', 'US'),
('MYF', 'San Diego', 'California', 'US'),
('MYL', 'Mc Call', 'Idaho', 'US'),
('MYR', 'Myrtle Beach', 'South-Carolina', 'US'),
('MYV', 'Marysville', 'California', 'US'),
('MZJ', 'Marana', 'Arizona', 'US'),
('MZZ', 'Marion', 'Indiana', 'US'),
('NBG', 'New Orleans', 'Louisiana', 'US'),
('NHX', 'Foley', 'Alabama', 'US'),
('DGN', 'Dahlgren', 'Virginia', 'US'),
('NEL', 'Lakehurst', 'New-Jersey', 'US'),
('NEN', 'Jacksonville', 'Florida', 'US'),
('NEW', 'New Orleans', 'Louisiana', 'US'),
('NFL', 'Fallon', 'Nevada', 'US'),
('FWH', 'Fort Worth', 'Texas', 'US'),
('NGP', 'Corpus Christi', 'Texas', 'US'),
('NGU', 'Norfolk', 'Virginia', 'US'),
('NGW', 'Corpus Christi', 'Texas', 'US'),
('NHK', 'Patuxent River', 'Maryland', 'US'),
('NIP', 'Jacksonville', 'Florida', 'US'),
('NJK', 'El Centro', 'California', 'US'),
('NKX', 'San Diego', 'California', 'US'),
('NLC', 'Lemoore', 'California', 'US'),
('NPA', 'Pensacola', 'Florida', 'US'),
('NQA', 'Millington', 'Tennessee', 'US'),
('NQI', 'Kingsville', 'Texas', 'US'),
('NQX', 'Key West', 'Florida', 'US'),
('NRB', 'Mayport', 'Florida', 'US'),
('NRS', 'Imperial Beach', 'California', 'US'),
('NSE', 'Milton', 'Florida', 'US'),
('NTD', 'Point Mugu', 'California', 'US'),
('NTU', 'Virginia Beach', 'Virginia', 'US'),
('NUN', 'Pensacola', 'Florida', 'US'),
('NUQ', 'Mountain View', 'California', 'US'),
('NUW', 'Oak Harbor', 'Washington', 'US'),
('NVD', 'Nevada', 'Missouri', 'US'),
('NYG', 'Quantico', 'Virginia', 'US'),
('YUM', 'Yuma', 'Arizona', 'US'),
('NZY', 'San Diego', 'California', 'US'),
('NVN', 'Beckwourth', 'California', 'US'),
('ODC', 'Oakdale', 'California', 'US'),
('EYR', 'Yerington', 'Nevada', 'US'),
('OAJ', 'Jacksonville', 'North-Carolina', 'US'),
('OAK', 'Oakland', 'California', 'US'),
('OAR', 'Marina', 'California', 'US'),
('OBE', 'Okeechobee', 'Florida', 'US'),
('OCF', 'Ocala', 'Florida', 'US'),
('OCH', 'Nacogdoches', 'Texas', 'US'),
('OCW', 'Washington', 'Georgia', 'US'),
('OEO', 'Osceola', 'Wisconsin', 'US'),
('OFF', 'Omaha', 'Nebraska', 'US'),
('OFK', 'Norfolk', 'Nebraska', 'US'),
('OGA', 'Ogallala', 'Nebraska', 'US'),
('OGB', 'Orangeburg', 'South-Carolina', 'US'),
('OGD', 'Ogden', 'Utah', 'US'),
('OGS', 'Ogdensburg', 'New-York', 'US'),
('OIC', 'Norwich', 'New-York', 'US'),
('OJC', 'Olathe', 'Kansas', 'US'),
('OCN', 'Oceanside', 'California', 'US'),
('OKC', 'Oklahoma City', 'Oklahoma', 'US'),
('ODW', 'Oak Harbor', 'Washington', 'US'),
('OKK', 'Kokomo', 'Indiana', 'US'),
('OKM', 'Okmulgee', 'Oklahoma', 'US'),
('OKS', 'Oshkosh', 'Nebraska', 'US'),
('WGO', 'Winchester', 'Virginia', 'US'),
('OLD', 'Old Town', 'Maine', 'US'),
('OLE', 'Olean', 'New-York', 'US'),
('OLF', 'Wolf Point', 'Montana', 'US'),
('OLM', 'Olympia', 'Washington', 'US'),
('OLS', 'Nogales', 'Arizona', 'US'),
('OLU', 'Columbus', 'Nebraska', 'US'),
('OLV', 'Olive Branch', 'Mississippi', 'US'),
('OLY', 'Olney-Noble', 'Illinois', 'US'),
('OMA', 'Omaha', 'Nebraska', 'US'),
('OMK', 'Omak', 'Washington', 'US'),
('ONA', 'Winona', 'Minnesota', 'US'),
('ONL', 'O\'Neill', 'Nebraska', 'US'),
('ONM', 'Socorro', 'New-Mexico', 'US'),
('ONO', 'Ontario', 'Oregon', 'US'),
('ONP', 'Newport', 'Oregon', 'US'),
('ONT', 'Ontario', 'California', 'US'),
('ONY', 'Olney', 'Texas', 'US'),
('OOA', 'Oskaloosa', 'Iowa', 'US'),
('OPF', 'Miami', 'Florida', 'US'),
('OPL', 'Opelousas', 'Louisiana', 'US'),
('NCO', 'North Kingstown', 'Rhode-Island', 'US'),
('ORD', 'Chicago', 'Illinois', 'US'),
('ORF', 'Norfolk', 'Virginia', 'US'),
('ORH', 'Worcester', 'Massachusetts', 'US'),
('ORL', 'Orlando', 'Florida', 'US'),
('ESD', 'Eastsound', 'Washington', 'US'),
('MPS', 'Mount Pleasant', 'Texas', 'US'),
('OSC', 'Oscoda', 'Michigan', 'US'),
('OSH', 'Oshkosh', 'Wisconsin', 'US'),
('OSU', 'Columbus', 'Ohio', 'US'),
('OSX', 'Kosciusko', 'Mississippi', 'US'),
('OTG', 'Worthington', 'Minnesota', 'US'),
('OTH', 'North Bend', 'Oregon', 'US'),
('OTM', 'Ottumwa', 'Iowa', 'US'),
('OUN', 'Norman', 'Oklahoma', 'US'),
('OVE', 'Oroville', 'California', 'US'),
('OWA', 'Owatonna', 'Minnesota', 'US'),
('OWB', 'Owensboro', 'Kentucky', 'US'),
('OWD', 'Norwood', 'Massachusetts', 'US'),
('OWK', 'Norridgewock', 'Maine', 'US'),
('OCE', 'Ocean City', 'Maryland', 'US'),
('OXC', 'Oxford', 'Connecticut', 'US'),
('OXD', 'Oxford', 'Ohio', 'US'),
('OXR', 'Oxnard', 'California', 'US'),
('STQ', 'St Marys', 'Pennsylvania', 'US'),
('OZA', 'Ozona', 'Texas', 'US'),
('OZR', 'Fort Rucker/Ozark', 'Alabama', 'US'),
('BSQ', 'Bisbee', 'Arizona', 'US'),
('HBK', 'Holbrook', 'Arizona', 'US'),
('CWX', 'Willcox', 'Arizona', 'US'),
('PAE', 'Everett', 'Washington', 'US'),
('PAH', 'Paducah', 'Kentucky', 'US'),
('PAM', 'Panama City', 'Florida', 'US'),
('PJB', 'Payson', 'Arizona', 'US'),
('PAO', 'Palo Alto', 'California', 'US'),
('PBF', 'Pine Bluff', 'Arkansas', 'US'),
('PBG', 'Plattsburgh', 'New-York', 'US'),
('PBI', 'West Palm Beach', 'Florida', 'US'),
('PVL', 'Pikeville', 'Kentucky', 'US'),
('PCD', 'Prairie Du Chien', 'Wisconsin', 'US'),
('PDK', 'Atlanta', 'Georgia', 'US'),
('PDT', 'Pendleton', 'Oregon', 'US'),
('PDX', 'Portland', 'Oregon', 'US'),
('PEQ', 'Pecos', 'Texas', 'US'),
('PFC', 'Pacific City', 'Oregon', 'US'),
('PFN', 'Panama City', 'Florida', 'US'),
('PGA', 'Page', 'Arizona', 'US'),
('PGD', 'Punta Gorda', 'Florida', 'US'),
('PGR', 'Paragould', 'Arkansas', 'US'),
('PGV', 'Greenville', 'North-Carolina', 'US'),
('PHD', 'New Philadelphia', 'Ohio', 'US'),
('PHF', 'Newport News', 'Virginia', 'US'),
('ADR', 'Andrews', 'South-Carolina', 'US'),
('PHK', 'Pahokee', 'Florida', 'US'),
('PHL', 'Philadelphia', 'Pennsylvania', 'US'),
('PHN', 'Port Huron', 'Michigan', 'US'),
('PHP', 'Philip', 'South-Dakota', 'US'),
('PHT', 'Paris', 'Tennessee', 'US'),
('PHX', 'Phoenix', 'Arizona', 'US'),
('PIA', 'Peoria', 'Illinois', 'US'),
('PIB', 'Hattiesburg/Laurel', 'Mississippi', 'US'),
('PIE', 'St Petersburg-Clearwater', 'Florida', 'US'),
('PIH', 'Pocatello', 'Idaho', 'US'),
('PIM', 'Pine Mountain', 'Georgia', 'US'),
('PIR', 'Pierre', 'South-Dakota', 'US'),
('PIT', 'Pittsburgh', 'Pennsylvania', 'US'),
('PKB', 'Parkersburg', 'West-Virginia', 'US'),
('PKD', 'Park Rapids', 'Minnesota', 'US'),
('PKF', 'Park Falls', 'Wisconsin', 'US'),
('PLK', 'Point Lookout', 'Missouri', 'US'),
('PLN', 'Pellston', 'Michigan', 'US'),
('PLR', 'Pell City', 'Alabama', 'US'),
('PMB', 'Pembina', 'North-Dakota', 'US'),
('PMD', 'Palmdale', 'California', 'US'),
('PMH', 'Portsmouth', 'Ohio', 'US'),
('PPM', 'Pompano Beach', 'Florida', 'US'),
('PWY', 'Pinedale', 'Wyoming', 'US'),
('PNC', 'Ponca City', 'Oklahoma', 'US'),
('PNE', 'Philadelphia', 'Pennsylvania', 'US'),
('PNN', 'Princeton', 'Maine', 'US'),
('PNS', 'Pensacola', 'Florida', 'US'),
('POB', 'Fayetteville', 'North-Carolina', 'US'),
('POC', 'La Verne', 'Minnesota', 'US'),
('POE', 'Fort Polk', 'Louisiana', 'US'),
('POF', 'Poplar Bluff', 'Missouri', 'US'),
('POH', 'Pocahontas', 'Iowa', 'US'),
('POU', 'Poughkeepsie', 'New-York', 'US'),
('POY', 'Powell', 'Wyoming', 'US'),
('PPA', 'Pampa', 'Texas', 'US'),
('PPF', 'Parsons', 'Kansas', 'US'),
('LPO', 'La Porte', 'Indiana', 'US'),
('PQI', 'Presque Isle', 'Maine', 'US'),
('PGL', 'Pascagoula', 'Mississippi', 'US'),
('PRB', 'Paso Robles', 'California', 'US'),
('PRC', 'Prescott', 'Arizona', 'US'),
('PRO', 'Perry', 'Iowa', 'US'),
('PRX', 'Paris', 'Texas', 'US'),
('PSB', 'Philipsburg', 'Pennsylvania', 'US'),
('PSC', 'Pasco', 'Washington', 'US'),
('PSF', 'Pittsfield', 'Massachusetts', 'US'),
('PSK', 'Dublin', 'Virginia', 'US'),
('PSM', 'Portsmouth', 'New-Hampshire', 'US'),
('PSN', 'Palestine', 'Texas', 'US'),
('PGO', 'Pagosa Springs', 'Colorado', 'US'),
('PSP', 'Palm Springs', 'California', 'US'),
('PSX', 'Palacios', 'Texas', 'US'),
('PTB', 'Petersburg', 'Virginia', 'US'),
('PTK', 'Pontiac', 'Michigan', 'US'),
('PTN', 'Patterson', 'Louisiana', 'US'),
('PTS', 'Pittsburg', 'Kansas', 'US'),
('PTT', 'Pratt', 'Kansas', 'US'),
('PTV', 'Porterville', 'California', 'US'),
('PTW', 'Pottstown', 'Pennsylvania', 'US'),
('PUB', 'Pueblo', 'Colorado', 'US'),
('PUC', 'Price', 'Utah', 'US'),
('PUW', 'Pullman/Moscow', 'Washington', 'US'),
('PVC', 'Provincetown', 'Massachusetts', 'US'),
('PVD', 'Providence', 'Rhode-Island', 'US'),
('PVF', 'Placerville', 'California', 'US'),
('PVU', 'Provo', 'Utah', 'US'),
('PVW', 'Plainview', 'Texas', 'US'),
('PWA', 'Oklahoma City', 'Oklahoma', 'US'),
('PWD', 'Plentywood', 'Montana', 'US'),
('PWM', 'Portland', 'Maine', 'US'),
('PWT', 'Bremerton', 'Washington', 'US'),
('PYM', 'Plymouth', 'Indiana', 'US'),
('RAC', 'Racine', 'Wisconsin', 'US'),
('RAL', 'Riverside', 'California', 'US'),
('RAP', 'Rapid City', 'South-Dakota', 'US'),
('RBD', 'Dallas', 'Texas', 'US'),
('RBG', 'Roseburg', 'Oregon', 'US'),
('RBL', 'Red Bluff', 'California', 'US'),
('RBW', 'Walterboro', 'South-Carolina', 'US'),
('RCA', 'Rapid City', 'South-Dakota', 'US'),
('RCK', 'Rockdale', 'Texas', 'US'),
('RCR', 'Rochester', 'Indiana', 'US'),
('RCT', 'Reed City', 'Michigan', 'US'),
('RDD', 'Redding', 'California', 'US'),
('RDG', 'Reading', 'Pennsylvania', 'US'),
('RDM', 'Redmond', 'Oregon', 'US'),
('RDR', 'Grand Forks', 'North-Dakota', 'US'),
('RDU', 'Raleigh/Durham', 'North-Carolina', 'US'),
('REO', 'Rome', 'Oregon', 'US'),
('RFD', 'Chicago/Rockford', 'Illinois', 'US'),
('RFG', 'Refugio', 'Texas', 'US'),
('RHI', 'Rhinelander', 'Wisconsin', 'US'),
('RHV', 'San Jose', 'California', 'US'),
('RIC', 'Richmond', 'Virginia', 'US'),
('RID', 'Richmond', 'Indiana', 'US'),
('RIF', 'Richfield', 'Utah', 'US'),
('RIL', 'Rifle', 'Colorado', 'US'),
('RIR', 'Riverside/Rubidoux/', 'California', 'US'),
('RIV', 'Riverside', 'California', 'US'),
('RIW', 'Riverton', 'Wyoming', 'US'),
('RKD', 'Rockland', 'Maine', 'US'),
('RKP', 'Rockport', 'Texas', 'US'),
('RKR', 'Poteau', 'Oklahoma', 'US'),
('RKS', 'Rock Springs', 'Wyoming', 'US'),
('RKW', 'Rockwood', 'Tennessee', 'US'),
('RLD', 'Richland', 'Washington', 'US'),
('RME', 'Rome', 'New-York', 'US'),
('RMG', 'Rome', 'Georgia', 'US'),
('RNC', 'Mc Minnville', 'Tennessee', 'US'),
('RND', 'Universal City', 'Texas', 'US'),
('RNH', 'New Richmond', 'Wisconsin', 'US'),
('RNO', 'Reno', 'Nevada', 'US'),
('RNT', 'Renton', 'Washington', 'US'),
('ROA', 'Roanoke', 'Virginia', 'US'),
('ROC', 'Rochester', 'New-York', 'US'),
('ROG', 'Rogers', 'Arkansas', 'US'),
('ROW', 'Roswell', 'New-Mexico', 'US'),
('ROX', 'Roseau', 'Minnesota', 'US'),
('RIE', 'Rice Lake', 'Wisconsin', 'US'),
('RPX', 'Roundup', 'Montana', 'US'),
('WBR', 'Big Rapids', 'Michigan', 'US'),
('RQO', 'El Reno', 'Oklahoma', 'US'),
('RRL', 'Merrill', 'Wisconsin', 'US'),
('RRT', 'Warroad', 'Minnesota', 'US'),
('RSL', 'Russell', 'Kansas', 'US'),
('RSN', 'Ruston', 'Louisiana', 'US'),
('RST', 'Rochester', 'Minnesota', 'US'),
('RSW', 'Fort Myers', 'Florida', 'US'),
('RTN', 'Raton', 'New-Mexico', 'US'),
('SRW', 'Salisbury', 'North-Carolina', 'US'),
('RUT', 'Rutland', 'Vermont', 'US'),
('RED', 'Reedsville', 'Pennsylvania', 'US'),
('RVS', 'Tulsa', 'Oklahoma', 'US'),
('RWF', 'Redwood Falls', 'Minnesota', 'US'),
('RWI', 'Rocky Mount', 'North-Carolina', 'US'),
('RWL', 'Rawlins', 'Wyoming', 'US'),
('RXE', 'Rexburg', 'Idaho', 'US'),
('RNZ', 'Rensselaer', 'Indiana', 'US'),
('RZZ', 'Roanoke Rapids', 'North-Carolina', 'US'),
('AHM', 'Ashland', 'Oregon', 'US'),
('BDY', 'Bandon', 'Oregon', 'US'),
('SUO', 'Sunriver', 'Oregon', 'US'),
('VSK', 'Kennewick', 'Washington', 'US'),
('SAA', 'Saratoga', 'Wyoming', 'US'),
('SAC', 'Sacramento', 'California', 'US'),
('SAD', 'Safford', 'Arizona', 'US'),
('SAF', 'Santa Fe', 'New-Mexico', 'US'),
('SAN', 'San Diego', 'California', 'US'),
('SAR', 'Sparta', 'Illinois', 'US'),
('SAS', 'Salton City', 'California', 'US'),
('SAT', 'San Antonio', 'Texas', 'US'),
('SAV', 'Savannah', 'Georgia', 'US'),
('MQT', 'Marquette', 'Michigan', 'US'),
('SBA', 'Santa Barbara', 'California', 'US'),
('SBD', 'San Bernardino', 'California', 'US'),
('SBM', 'Sheboygan', 'Wisconsin', 'US'),
('SBN', 'South Bend', 'Indiana', 'US'),
('SBP', 'San Luis Obispo', 'California', 'US'),
('SBS', 'Steamboat Springs', 'Colorado', 'US'),
('SBX', 'Shelby', 'Montana', 'US'),
('SBY', 'Salisbury', 'Maryland', 'US'),
('SCB', 'Scribner', 'Nebraska', 'US'),
('SCH', 'Schenectady', 'New-York', 'US'),
('SCK', 'Stockton', 'California', 'US'),
('SDF', 'Louisville', 'Kentucky', 'US'),
('SCF', 'Scottsdale', 'Arizona', 'US'),
('SDM', 'San Diego', 'California', 'US'),
('SDY', 'Sidney', 'Montana', 'US'),
('SEA', 'Seattle', 'Washington', 'US'),
('SEE', 'San Diego/El Cajon', 'California', 'US'),
('SEF', 'Sebring', 'Florida', 'US'),
('SEG', 'Selinsgrove', 'Pennsylvania', 'US'),
('SEM', 'Selma', 'Alabama', 'US'),
('SEP', 'Stephenville', 'Texas', 'US'),
('SER', 'Seymour', 'Indiana', 'US'),
('SDX', 'Sedona', 'Arizona', 'US'),
('SFB', 'Orlando', 'Florida', 'US'),
('SFF', 'Spokane', 'Oregon', 'US'),
('SFM', 'Sanford', 'Maine', 'US'),
('SFO', 'San Francisco', 'California', 'US'),
('SFZ', 'Pawtucket', 'Rhode-Island', 'US'),
('SGF', 'Springfield', 'Missouri', 'US'),
('SGH', 'Springfield', 'Ohio', 'US'),
('UST', 'St Augustine', 'Florida', 'US'),
('SGR', 'Houston', 'Texas', 'US'),
('SGT', 'Stuttgart', 'Arkansas', 'US'),
('SGU', 'St George', 'Utah', 'US'),
('SHD', 'Staunton/Waynesboro/Harrisonburg', 'Virginia', 'US'),
('SHN', 'Shelton', 'Washington', 'US'),
('SHR', 'Sheridan', 'Wyoming', 'US'),
('SHV', 'Shreveport', 'Louisiana', 'US'),
('SIK', 'Sikeston', 'Missouri', 'US'),
('SIV', 'Sullivan', 'Indiana', 'US'),
('SIY', 'Montague', 'California', 'US'),
('SJC', 'San Jose', 'California', 'US'),
('SJN', 'St Johns', 'Arizona', 'US'),
('SJT', 'San Angelo', 'Texas', 'US'),
('SKA', 'Spokane', 'Washington', 'US'),
('SKF', 'San Antonio', 'Texas', 'US'),
('TSM', 'Taos', 'New-Mexico', 'US'),
('SLB', 'Storm Lake', 'Iowa', 'US'),
('SLC', 'Salt Lake City', 'Utah', 'US'),
('SLE', 'Salem', 'Oregon', 'US'),
('SLG', 'Siloam Springs', 'Arkansas', 'US'),
('SLK', 'Saranac Lake', 'New-York', 'US'),
('SLN', 'Salina', 'Kansas', 'US'),
('SLO', 'Salem', 'Illinois', 'US'),
('SLR', 'Sulphur Springs', 'Texas', 'US'),
('SMD', 'Fort Wayne', 'Arkansas', 'US'),
('SME', 'Somerset', 'Kentucky', 'US'),
('SMF', 'Sacramento', 'California', 'US'),
('SMN', 'Salmon', 'Idaho', 'US'),
('SMO', 'Santa Monica', 'California', 'US'),
('SUM', 'Sumter', 'South-Carolina', 'US'),
('SMX', 'Santa Maria', 'California', 'US'),
('SNA', 'Santa Ana', 'California', 'US'),
('SNK', 'Snyder', 'Texas', 'US'),
('SNL', 'Shawnee', 'Oklahoma', 'US'),
('SNS', 'Salinas', 'California', 'US'),
('SNY', 'Sidney', 'Nebraska', 'US'),
('SOP', 'Pinehurst/Southern Pines', 'North-Carolina', 'US'),
('SOW', 'Show Low', 'Arizona', 'US'),
('SPA', 'Spartanburg', 'South-Carolina', 'US'),
('SPF', 'Spearfish', 'South-Dakota', 'US'),
('SPG', 'St Petersburg', 'Florida', 'US'),
('SPI', 'Springfield', 'Illinois', 'US'),
('SPS', 'Wichita Falls', 'Texas', 'US'),
('SPW', 'Spencer', 'Iowa', 'US'),
('SQI', 'Sterling/Rockfalls', 'Illinois', 'US'),
('SQL', 'San Carlos', 'Arizona', 'US'),
('SRC', 'Searcy', 'Arkansas', 'US'),
('SRQ', 'Sarasota/Bradenton', 'Florida', 'US'),
('RUI', 'Ruidoso', 'New-Mexico', 'US'),
('SSC', 'Sumter', 'South-Carolina', 'US'),
('SSF', 'San Antonio', 'Texas', 'US'),
('SSI', 'Brunswick', 'Georgia', 'US'),
('STC', 'St Cloud', 'Minnesota', 'US'),
('STE', 'Stevens Point', 'Wisconsin', 'US'),
('STJ', 'St Joseph', 'Missouri', 'US'),
('STK', 'Sterling', 'Colorado', 'US'),
('STL', 'St Louis', 'Missouri', 'US'),
('STP', 'St Paul', 'Minnesota', 'US'),
('STS', 'Santa Rosa', 'California', 'US'),
('SUA', 'Stuart', 'Florida', 'US'),
('SUD', 'Stroud', 'Oklahoma', 'US'),
('SUE', 'Sturgeon Bay', 'Wisconsin', 'US'),
('SUN', 'Hailey', 'Idaho', 'US'),
('SUS', 'St Louis', 'Missouri', 'US'),
('SUU', 'Fairfield', 'California', 'US'),
('SUW', 'Superior', 'Wisconsin', 'US'),
('SUX', 'Sioux City', 'Iowa', 'US'),
('SVC', 'Silver City', 'New-Mexico', 'US'),
('SVE', 'Susanville', 'California', 'US'),
('SVH', 'Statesville', 'North-Carolina', 'US'),
('SVN', 'Savannah', 'Georgia', 'US'),
('SWF', 'Newburgh', 'New-York', 'US'),
('SWO', 'Stillwater', 'Oklahoma', 'US'),
('SWW', 'Sweetwater', 'Texas', 'US'),
('SYI', 'Shelbyville', 'Tennessee', 'US'),
('SYN', 'Stanton', 'Minnesota', 'US'),
('SYR', 'Syracuse', 'New-York', 'US'),
('SYV', 'Sylvester', 'Georgia', 'US'),
('SZL', 'Knob Noster', 'Missouri', 'US'),
('SZN', 'Santa Barbara', 'California', 'US'),
('SZP', 'Santa Paula', 'California', 'US'),
('TAD', 'Trinidad', 'Colorado', 'US'),
('TBN', 'Fort Leonard Wood', 'Missouri', 'US'),
('TBR', 'Statesboro', 'Georgia', 'US'),
('TCC', 'Tucumcari', 'New-Mexico', 'US'),
('TCL', 'Tuscaloosa', 'Alabama', 'US'),
('TCM', 'Tacoma', 'Washington', 'US'),
('TCS', 'Truth Or Consequences', 'New-Mexico', 'US'),
('TDO', 'Toledo', 'Washington', 'US'),
('TDW', 'Amarillo', 'Texas', 'US'),
('TDZ', 'Toledo', 'Ohio', 'US'),
('TEB', 'Teterboro', 'New-Jersey', 'US'),
('TEX', 'Telluride', 'Colorado', 'US'),
('THA', 'Tullahoma', 'Tennessee', 'US'),
('THM', 'Thompson Falls', 'Montana', 'US'),
('THP', 'Thermopolis', 'Wyoming', 'US'),
('THV', 'York', 'Pennsylvania', 'US'),
('TIK', 'Oklahoma City', 'Oklahoma', 'US'),
('TIW', 'Tacoma', 'Washington', 'US'),
('TIX', 'Titusville', 'Florida', 'US'),
('KNT', 'Kennett', 'Missouri', 'US'),
('TLH', 'Tallahassee', 'Florida', 'US'),
('TLR', 'Tulare', 'California', 'US'),
('TMA', 'Tifton', 'Georgia', 'US'),
('TMB', 'Miami', 'Miami', 'US'),
('OTK', 'Tillamook', 'Oregon', 'US'),
('ASQ', 'Austin', 'Nevada', 'US'),
('TNP', 'Twentynine Palms', 'California', 'US'),
('TNT', 'Miami', 'Florida', 'US'),
('TNU', 'Newton', 'Iowa', 'US'),
('XSD', 'Tonopah', 'Nevada', 'US'),
('TOA', 'Torrance', 'California', 'US'),
('TOC', 'Toccoa', 'Georgia', 'US'),
('TOI', 'Troy', 'Alabama', 'US'),
('TOL', 'Toledo', 'Ohio', 'US'),
('TOP', 'Topeka', 'Kansas', 'US'),
('TOR', 'Torrington', 'Wyoming', 'US'),
('TPA', 'Tampa', 'Florida', 'US'),
('TPF', 'Tampa', 'Florida', 'US'),
('TPH', 'Tonopah', 'Nevada', 'US'),
('TPL', 'Temple', 'Texas', 'US'),
('TRI', 'Bristol/Johnson/Kingsport', 'Tennessee', 'US'),
('TKF', 'Truckee', 'California', 'US'),
('TRL', 'Terrell', 'Texas', 'US'),
('TRM', 'Palm Springs', 'California', 'US'),
('TRX', 'Trenton', 'Missouri', 'US'),
('TSP', 'Tehachapi', 'California', 'US'),
('TTD', 'Portland', 'Oregon', 'US'),
('TTN', 'Trenton', 'New-Jersey', 'US'),
('TUL', 'Tulsa', 'Oklahoma', 'US'),
('TUP', 'Tupelo', 'Mississippi', 'US'),
('TUS', 'Tucson', 'Arizona', 'US'),
('TVC', 'Traverse City', 'Michigan', 'US'),
('TVF', 'Thief River Falls', 'Minnesota', 'US'),
('TVI', 'Thomasville', 'Georgia', 'US'),
('TVL', 'South Lake Tahoe', 'California', 'US'),
('TWF', 'Twin Falls', 'Idaho', 'US'),
('TXK', 'Texarkana', 'Arkansas', 'US'),
('TYZ', 'Taylor', 'Arizona', 'US'),
('TYR', 'Tyler', 'Texas', 'US'),
('TYS', 'Knoxville', 'Tennessee', 'US'),
('BFG', 'Glen Canyon Natl Rec Area', 'Utah', 'US'),
('RVR', 'Green River', 'Utah', 'US'),
('ICS', 'Cascade', 'Idaho', 'US'),
('UBS', 'Columbus', 'Mississippi', 'US'),
('UCY', 'Union City', 'Tennessee', 'US'),
('UDD', 'Palm Springs', 'California', 'US'),
('UES', 'Waukesha', 'Wisconsin', 'US'),
('UGN', 'Chicago/Waukegan', 'Illinois', 'US'),
('UIL', 'Quillayute', 'Washington', 'US'),
('UIN', 'Quincy', 'Illinois', 'US'),
('IKB', 'North Wilkesboro', 'North-Carolina', 'US'),
('UKI', 'Ukiah', 'California', 'US'),
('UKT', 'Quakertown', 'Pennsylvania', 'US'),
('ULM', 'New Ulm', 'Minnesota', 'US'),
('ATO', 'Athens/Albany', 'Ohio', 'US'),
('UNU', 'Juneau', 'Wisconsin', 'US'),
('SCE', 'State College', 'Pennsylvania', 'US'),
('UOS', 'Sewanee', 'Georgia', 'US'),
('UOX', 'Oxford', 'Mississippi', 'US'),
('UTM', 'Tunica', 'Mississippi', 'US'),
('HTV', 'Huntsville', 'Texas', 'US'),
('NPT', 'Newport', 'Rhode-Island', 'US'),
('UVA', 'Uvalde', 'Florida', 'US'),
('RKH', 'Rock Hill', 'South-Carolina', 'US'),
('VAD', 'Valdosta', 'Georgia', 'US'),
('LLY', 'Mount Holly', 'New-Jersey', 'US'),
('VBG', 'Lompoc', 'California', 'US'),
('VCT', 'Victoria', 'Texas', 'US'),
('VCV', 'Victorville', 'California', 'US'),
('VDI', 'Vidalia', 'Georgia', 'US'),
('VEL', 'Vernal', 'Utah', 'US'),
('VGT', 'Las Vegas', 'Nevada', 'US'),
('VHN', 'Van Horn', 'Texas', 'US'),
('VIH', 'Rolla/Vichy', 'Missouri', 'US'),
('VIS', 'Visalia', 'California', 'US'),
('VJI', 'Abingdon', 'Virginia', 'US'),
('VKS', 'Vicksburg', 'Mississippi', 'US'),
('VKX', 'Friendly', 'Maryland', 'US'),
('VLA', 'Vandalia', 'Illinois', 'US'),
('VLD', 'Valdosta', 'Georgia', 'US'),
('VNC', 'Venice', 'Florida', 'US'),
('VNY', 'Van Nuys', 'California', 'US'),
('VOK', 'Camp Douglas', 'Wisconsin', 'US'),
('VPS', 'Valparaiso', 'Florida', 'US'),
('VPZ', 'Valparaiso', 'Indiana', 'US'),
('VQQ', 'Jacksonville', 'Florida', 'US'),
('VRB', 'Vero Beach', 'Florida', 'US'),
('VSF', 'Springfield', 'Vermont', 'US'),
('VTN', 'Valentine', 'Nebraska', 'US'),
('VYS', 'Peru', 'Illinois', 'US'),
('WAL', 'Wallops Island', 'Virginia', 'US'),
('WAY', 'Waynesburg', 'Pennsylvania', 'US'),
('WBW', 'Wilkes-Barre', 'Pennsylvania', 'US'),
('WDG', 'Enid', 'Oklahoma', 'US'),
('WDR', 'Winder', 'Georgia', 'US'),
('WHP', 'Los Angeles', 'California', 'US'),
('WJF', 'Lancaster', 'California', 'US'),
('WLD', 'Winfield/Arkansas City', 'Kansas', 'US'),
('WLW', 'Willows', 'California', 'US'),
('WMC', 'Winnemucca', 'Nevada', 'US'),
('WRB', 'Warner Robins', 'Georgia', 'US'),
('WRI', 'Wrightstown', 'New-Jersey', 'US'),
('WRL', 'Worland', 'Wyoming', 'US'),
('WSD', 'White Sands', 'New-Mexico', 'US'),
('WST', 'Westerly', 'Rhode-Island', 'US'),
('WVI', 'Watsonville', 'California', 'US'),
('WVL', 'Waterville', 'Maine', 'US'),
('WWD', 'Wildwood', 'New-Jersey', 'US'),
('WWR', 'Woodward', 'Oklahoma', 'US'),
('WYS', 'West Yellowstone', 'Montana', 'US'),
('XNA', 'Fayetteville/Springdale/', 'Arkansas', 'US'),
('YIP', 'Detroit', 'Michigan', 'US'),
('YKM', 'Yakima', 'Washington', 'US'),
('YKN', 'Yankton', 'South-Dakota', 'US'),
('YNG', 'Youngstown/Warren', 'Ohio', 'US'),
('ZPH', 'Zephyrhills', 'Florida', 'US'),
('ZZV', 'Zanesville', 'Ohio', 'US'),
('DPE', 'Dieppe', 'Normandy', 'FR'),
('CQF', 'Marck', 'Hauts-de-France', 'FR'),
('XCP', 'Compiegne', 'Hauts-de-France', 'FR'),
('XLN', 'Laon-Chambry', 'Hauts-de-France', 'FR'),
('XSJ', 'Peronne/Saint-Quentin', 'Hauts-de-France', 'FR'),
('XDK', 'Les Moeres', 'Hauts-de-France', 'FR'),
('BYF', 'Albert/Bray', 'Hauts-de-France', 'FR'),
('LTQ', 'Le Touquet-Paris-Plage', 'Hauts-de-France', 'FR'),
('XVS', 'Valenciennes/Denain', 'Hauts-de-France', 'FR'),
('QAM', 'Amiens/Glisy', 'Hauts-de-France', 'FR'),
('AGF', 'Agen/La Garenne', 'Nouvelle-Aquitaine', 'FR'),
('BOD', 'Bordeaux/Merignac', 'Nouvelle-Aquitaine', 'FR'),
('EGC', 'Bergerac/Roumaniere', 'Nouvelle-Aquitaine', 'FR'),
('CNG', 'Cognac/Chateaubernard', 'Nouvelle-Aquitaine', 'FR'),
('LRH', 'La Rochelle/Ile de Re', 'Nouvelle-Aquitaine', 'FR'),
('PIS', 'Poitiers/Biard', 'Nouvelle-Aquitaine', 'FR'),
('MCU', 'Montlucon/Gueret', 'Nouvelle-Aquitaine', 'FR'),
('LIG', 'Limoges/Bellegarde', 'Nouvelle-Aquitaine', 'FR'),
('XMJ', 'Mont-de-Marsan', 'Nouvelle-Aquitaine', 'FR'),
('NIT', 'Niort/Souche', 'Nouvelle-Aquitaine', 'FR'),
('TLS', 'Toulouse/Blagnac', 'Occitanie', 'FR'),
('PUF', 'Pau/Pyrenees (Uzein)', 'Nouvelle-Aquitaine', 'FR'),
('LDE', 'Tarbes/Lourdes/Pyrenees', 'Occitanie', 'FR'),
('ANG', 'Angouleme/Brie/Champniers', 'Nouvelle-Aquitaine', 'FR'),
('BVE', 'Brive-la-Gaillarde', 'Nouvelle-Aquitaine', 'FR'),
('PGX', 'Perigueux/Bassillac', 'Nouvelle-Aquitaine', 'FR'),
('XDA', 'Perigueux', 'Nouvelle-Aquitaine', 'FR'),
('BIQ', 'Biarritz/Anglet/Bayonne', 'Nouvelle-Aquitaine', 'FR'),
('XCX', 'Biarritz', 'Nouvelle-Aquitaine', 'FR'),
('ZAO', 'Cahors/Lalbenque', 'Occitanie', 'FR'),
('XGT', 'Cahors', 'Nouvelle-Aquitaine', 'FR'),
('XAC', 'Arcachon/La Teste-de-Buch', 'Nouvelle-Aquitaine', 'FR'),
('LBI', 'Albi/Le Sequestre', 'Occitanie', 'FR'),
('DCM', 'Castres/Mazamet', 'Occitanie', 'FR'),
('RDZ', 'Rodez/Marcillac', 'Occitanie', 'FR'),
('RYN', 'Royan/Medis', 'Nouvelle-Aquitaine', 'FR'),
('XMW', 'Montauban', 'Occitanie', 'FR'),
('XLR', 'Libourne/Artigues-de-Lussac', 'Nouvelle-Aquitaine', 'FR'),
('RCO', 'Rochefort/Saint-Agnant', 'Nouvelle-Aquitaine', 'FR'),
('XSL', 'Rochefort', 'Nouvelle-Aquitaine', 'FR'),
('XTB', 'Rochefort', 'Occitanie', 'FR'),
('IDY', 'Ile d\'Yeu', 'Pays-de-la-Loire', 'FR'),
('CMR', 'Colmar/Houssen', 'Grand-Est', 'FR'),
('XBV', 'Beaune/Challanges', 'Bourgogne-Franche-Comte', 'FR'),
('DLE', 'Dole/Tavaux', 'Bourgogne-Franche-Comte', 'FR'),
('XVN', 'Verdun/Le Rozelier', 'Grand-Est', 'FR'),
('MVV', 'Verdun', 'Auvergne-Rhone-Alpes', 'FR'),
('OBS', 'Aubenas/Ardeche Meridional', 'Auvergne-Rhone-Alpes', 'FR'),
('LPY', 'Le Puy/Loudes', 'Auvergne-Rhone-Alpes', 'FR'),
('XBK', 'Bourg/Ceyzeriat', 'Auvergne-Rhone-Alpes', 'FR'),
('AHZ', 'Bourg', 'Auvergne-Rhone-Alpes', 'FR'),
('XMU', 'Moulins/Montbeugny', 'Auvergne-Rhone-Alpes', 'FR'),
('ETZ', 'Metz / Nancy', 'Grand-Est', 'FR'),
('ANE', 'Angers/Marce', 'Pays-de-la-Loire', 'FR'),
('XAV', 'Angers', 'Auvergne-Rhone-Alpes', 'FR'),
('BIA', 'Bastia/Poretta', 'Corsica', 'FR'),
('CLY', 'Calvi/Sainte-Catherine', 'Corsica', 'FR'),
('FSC', 'Figari Sud-Corse', 'Corsica', 'FR'),
('AJA', 'Ajaccio/Napoleon Bonaparte', 'Corsica', 'FR'),
('PRP', 'Propriano', 'Corsica', 'FR'),
('SOZ', 'Solenzara', 'Corsica', 'FR'),
('MFX', 'Ajaccio', 'Auvergne-Rhone-Alpes', 'FR'),
('AUF', 'Auxerre/Branches', 'Bourgogne-Franche-Comte', 'FR'),
('CMF', 'Chambery/Aix-les-Bains', 'Auvergne-Rhone-Alpes', 'FR'),
('CFE', 'Clermont-Ferrand/Auvergne', 'Auvergne-Rhone-Alpes', 'FR'),
('BOU', 'Bourges', 'Centre', 'FR'),
('QNJ', 'Annemasse', 'Auvergne-Rhone-Alpes', 'FR'),
('CVF', 'Courcheval', 'Auvergne-Rhone-Alpes', 'FR'),
('LYS', 'Lyon', 'Auvergne-Rhone-Alpes', 'FR'),
('QNX', 'Macon/Charnay', 'Bourgogne-Franche-Comte', 'FR'),
('SYT', 'Saint-Yan', 'Bourgogne-Franche-Comte', 'FR'),
('RNE', 'Roanne/Renaison', 'Auvergne-Rhone-Alpes', 'FR'),
('NCY', 'Annecy/Meythet', 'Auvergne-Rhone-Alpes', 'FR'),
('XMK', 'Annecy', 'Auvergne-Rhone-Alpes', 'FR'),
('GNB', 'Grenoble/Saint-Geoirs', 'Auvergne-Rhone-Alpes', 'FR'),
('VAF', 'Valence/Chabeuil', 'Auvergne-Rhone-Alpes', 'FR'),
('VHY', 'Vichy/Charmeil', 'Auvergne-Rhone-Alpes', 'FR'),
('AUR', 'Aurillac', 'Auvergne-Rhone-Alpes', 'FR'),
('CHR', 'Chateauroux/Deols', 'Centre', 'FR'),
('LYN', 'Lyon/Bron', 'Auvergne-Rhone-Alpes', 'FR'),
('QXB', 'Lyon', 'Provence-Alpes-Cote-d\'Azur', 'FR'),
('CEQ', 'Cannes/Mandelieu', 'Provence-Alpes-Cote-d\'Azur', 'FR'),
('EBU', 'Saint-Etienne/Boutheon', 'Auvergne-Rhone-Alpes', 'FR'),
('QIE', 'Istres/Le Tube', 'Provence-Alpes-Cote-d\'Azur', 'FR'),
('CCF', 'Carcassonne/Salvaza', 'Occitanie', 'FR'),
('MRS', 'Marseille', 'Provence-Alpes-Cote-d\'Azur', 'FR'),
('NCE', 'Nice', 'Provence-Alpes-Cote-d\'Azur', 'FR'),
('XOG', 'Orange/Caritat', 'Provence-Alpes-Cote-d\'Azur', 'FR'),
('PGF', 'Perpignan/Rivesaltes', 'Occitanie', 'FR'),
('CTT', 'Le Castellet', 'Provence-Alpes-Cote-d\'Azur', 'FR'),
('BAE', 'Le Castellet', 'Provence-Alpes-Cote-d\'Azur', 'FR'),
('XAS', 'Ales/Deaux', 'Occitanie', 'FR'),
('MPL', 'Montpellier/Mediterranee', 'Occitanie', 'FR'),
('BZR', 'Beziers/Vias', 'Occitanie', 'FR'),
('AVN', 'Avignon/Caumont', 'Provence-Alpes-Cote-d\'Azur', 'FR'),
('GAT', 'Avignon', 'Provence-Alpes-Cote-d\'Azur', 'FR'),
('MEN', 'Mende/Brenoux', 'Occitanie', 'FR'),
('SCP', 'Mende', 'Provence-Alpes-Cote-d\'Azur', 'FR'),
('BVA', 'Beauvais/Tille', 'Hauts-de-France', 'FR'),
('XSU', 'Saumur/Saint-Florent', 'Pays-de-la-Loire', 'FR'),
('EVX', 'Evreux/Fauville', 'Normandy', 'FR'),
('XAN', 'Evreux', 'Normandy', 'FR'),
('LEH', 'Le Havre/Octeville', 'Normandy', 'FR'),
('XAB', 'Abbeville (Buigny/Saint-Maclou)', 'Hauts-de-France', 'FR'),
('ORE', 'Orleans/Bricy', 'Centre', 'FR'),
('XCR', 'Chalons/Vatry', 'Grand-Est', 'FR'),
('LSO', 'Les Sables-d\'Olonne', 'Pays-de-la-Loire', 'FR'),
('URO', 'Rouen/Vallee de Seine', 'Normandy', 'FR'),
('XBQ', 'Blois/Le Breuil', 'Centre', 'FR'),
('QTJ', 'Blois', 'Centre', 'FR'),
('TUF', 'Tours/Val de Loire (Loire Valley)', 'Centre', 'FR'),
('CET', 'Cholet/Le Pontreau', 'Pays-de-la-Loire', 'FR'),
('LVA', 'Laval/Entrammes', 'Pays-de-la-Loire', 'FR'),
('LBG', 'Paris', 'Ile-de-France', 'FR'),
('CSF', 'Creil', 'Hauts-de-France', 'FR'),
('CDG', 'Paris', 'Ile-de-France', 'FR'),
('TNF', 'Toussus-le-Noble', 'Ile-de-France', 'FR'),
('ORY', 'Paris', 'Ile-de-France', 'FR'),
('POX', 'Pontoise', 'Ile-de-France', 'FR'),
('VIY', 'Villacoublay/Velizy', 'Ile-de-France', 'FR'),
('QYR', 'Troyes/Barberey', 'Grand-Est', 'FR'),
('NVS', 'Nevers/Fourchambault', 'Bourgogne-Franche-Comte', 'FR'),
('XCB', 'Cambrai/Epinoy', 'Hauts-de-France', 'FR'),
('XME', 'Maubeuge/Elesmes', 'Hauts-de-France', 'FR'),
('LIL', 'Lille/Lesquin', 'Hauts-de-France', 'FR'),
('HZB', 'Merville/Calonne', 'Hauts-de-France', 'FR'),
('XCZ', 'Charleville-Mezieres', 'Grand-Est', 'FR'),
('XVO', 'Vesoul/Frotey', 'Bourgogne-Franche-Comte', 'FR'),
('BES', 'Brest/Guipavas', 'Brittany', 'FR'),
('CER', 'Cherbourg/Maupertus', 'Normandy', 'FR'),
('DNR', 'Dinard/Pleurtuit/Saint-Malo', 'Brittany', 'FR'),
('LBY', 'La Baule-Escoublac', 'Pays-de-la-Loire', 'FR'),
('GFR', 'Granville', 'Normandy', 'FR'),
('DOL', 'Deauville', 'Normandy', 'FR'),
('LRT', 'Lorient/Lann/Bihoue', 'Brittany', 'FR'),
('EDM', 'La Roche-sur-Yon/Les Ajoncs', 'Pays-de-la-Loire', 'FR'),
('LDV', 'Landivisiau', 'Brittany', 'FR'),
('CFR', 'Caen/Carpiquet', 'Normandy', 'FR'),
('LME', 'Le Mans/Arnage', 'Pays-de-la-Loire', 'FR'),
('RNS', 'Rennes/Saint-Jacques', 'Brittany', 'FR'),
('LAI', 'Lannion', 'Brittany', 'FR'),
('UIP', 'Quimper/Pluguffan', 'Brittany', 'FR'),
('NTE', 'Nantes', 'Pays-de-la-Loire', 'FR'),
('SBK', 'Saint-Brieuc/Armor', 'Brittany', 'FR'),
('MXN', 'Morlaix/Ploujean', 'Brittany', 'FR'),
('VNE', 'Vannes/Meucon', 'Brittany', 'FR'),
('SNR', 'Saint-Nazaire/Montoir', 'Pays-de-la-Loire', 'FR'),
('QBQ', 'St Nazaire', 'Bourgogne-Franche-Comte', 'FR'),
('BSL', 'Bale/Mulhouse', 'Grand-Est', 'FR'),
('DIJ', 'Dijon/Longvic', 'Bourgogne-Franche-Comte', 'FR'),
('MZM', 'Metz/Frescaty', 'Grand-Est', 'FR'),
('EPL', 'Epinal/Mirecourt', 'Grand-Est', 'FR'),
('XMF', 'Montbeliard/Courcelles', 'Bourgogne-Franche-Comte', 'FR'),
('ENC', 'Nancy/Essey', 'Grand-Est', 'FR'),
('BOR', 'Belfort', 'Bourgogne-Franche-Comte', 'FR'),
('RHE', 'Reims/Champagne', 'Grand-Est', 'FR'),
('SXB', 'Strasbourg', 'Grand-Est', 'FR'),
('VTL', 'Luxeuil', 'Grand-Est', 'FR'),
('TLN', 'Toulon/Hyeres/Le Palyvestre', 'Provence-Alpes-Cote-d\'Azur', 'FR'),
('FNI', 'Nimes/Garons', 'Occitanie', 'FR'),
('LTT', 'La Mole', 'Provence-Alpes-Cote-d\'Azur', 'FR'),
('DWN', 'Oklahoma City', 'Oklahoma', 'US'),
('AKB', 'Atka', 'Alaska', 'US'),
('PML', 'Cold Bay', 'Alaska', 'US'),
('PAQ', 'Palmer', 'Alaska', 'US'),
('BTI', 'Barter Island Lrrs', 'Alaska', 'US'),
('BET', 'Bethel', 'Alaska', 'US'),
('BVU', 'Beluga', 'Alaska', 'US'),
('BIG', 'Delta Junction Ft Greely', 'Alaska', 'US'),
('BKC', 'Buckland', 'Alaska', 'US'),
('BMX', 'Big Mountain', 'Alaska', 'US'),
('BRW', 'Barrow', 'Alaska', 'US'),
('BTT', 'Bettles', 'Alaska', 'US'),
('CDB', 'Cold Bay', 'Alaska', 'US'),
('CEM', 'Central', 'Alaska', 'US'),
('CHU', 'Chuathbaluk', 'Alaska', 'US'),
('CIK', 'Chalkyitsik', 'Alaska', 'US'),
('CYF', 'Chefornak', 'Alaska', 'US'),
('SCM', 'Scammon Bay', 'Alaska', 'US'),
('IRC', 'Circle', 'Alaska', 'US'),
('WSF', 'Cape Sarichef', 'Alaska', 'US'),
('CDV', 'Cordova', 'Alaska', 'US'),
('CXF', 'Coldfoot', 'Alaska', 'US'),
('CYT', 'Yakataga', 'Alaska', 'US'),
('CZF', 'Cape Romanzof', 'Alaska', 'US'),
('DRG', 'Deering', 'Alaska', 'US'),
('RDB', 'Red Dog', 'Alaska', 'US'),
('ADK', 'Adak Island', 'Alaska', 'US'),
('DLG', 'Dillingham', 'Alaska', 'US'),
('MLL', 'Marshall', 'Alaska', 'US'),
('ADQ', 'Kodiak', 'Alaska', 'US'),
('DUT', 'Unalaska', 'Alaska', 'US'),
('KKH', 'Kongiganak', 'Alaska', 'US'),
('EDF', 'Anchorage', 'Alaska', 'US'),
('EEK', 'Eek', 'Alaska', 'US'),
('EAA', 'Eagle', 'Alaska', 'US'),
('EHM', 'Cape Newenham', 'Alaska', 'US'),
('EIL', 'Fairbanks', 'Alaska', 'US'),
('EMK', 'Emmonak', 'Alaska', 'US'),
('ENA', 'Kenai', 'Alaska', 'US'),
('WWT', 'Newtok', 'Alaska', 'US'),
('FAI', 'Fairbanks', 'Alaska', 'US'),
('FBK', 'Fairbanks/Ft Wainwright', 'Alaska', 'US'),
('AFE', 'Kake', 'Alaska', 'US'),
('ABL', 'Ambler', 'Alaska', 'US'),
('NIB', 'Nikolai', 'Alaska', 'US'),
('FMC', 'Five Mile', 'Alaska', 'US'),
('FWL', 'Farewell', 'Alaska', 'US'),
('GAL', 'Galena', 'Alaska', 'US'),
('GBH', 'Galbraith Lake', 'Alaska', 'US'),
('KWK', 'Kwigillingok', 'Alaska', 'US'),
('GKN', 'Gulkana', 'Alaska', 'US'),
('GLV', 'Golovin', 'Alaska', 'US'),
('GAM', 'Gambell', 'Alaska', 'US'),
('GST', 'Gustavus', 'Alaska', 'US'),
('NME', 'Nightmute', 'Alaska', 'US'),
('SGY', 'Skagway', 'Alaska', 'US'),
('GMT', 'Granite Mountain', 'Alaska', 'US'),
('HCR', 'Holy Cross', 'Alaska', 'US'),
('HNE', 'Tahneta Pass Lodge', 'Alaska', 'US'),
('HSL', 'Huslia', 'Alaska', 'US'),
('HNS', 'Haines', 'Alaska', 'US'),
('HOM', 'Homer', 'Alaska', 'US'),
('HPB', 'Hooper Bay', 'Alaska', 'US'),
('HUS', 'Hughes', 'Alaska', 'US'),
('SHX', 'Shageluk', 'Alaska', 'US'),
('IGG', 'Igiugig', 'Alaska', 'US'),
('EGX', 'Egegik', 'Alaska', 'US'),
('IAN', 'Kiana', 'Alaska', 'US'),
('ILI', 'Iliamna', 'Alaska', 'US'),
('UTO', 'Utopia Creek', 'Alaska', 'US'),
('MCL', 'Mckinley Park', 'Alaska', 'US'),
('WAA', 'Wales', 'Alaska', 'US'),
('JNU', 'Juneau', 'Alaska', 'US'),
('KGK', 'Koliganek', 'Alaska', 'US'),
('KDK', 'Kodiak', 'Alaska', 'US'),
('KFP', 'False Pass', 'Alaska', 'US'),
('AKK', 'Akhiok', 'Alaska', 'US'),
('KPN', 'Kipnuk', 'Alaska', 'US'),
('KKA', 'Koyuk', 'Alaska', 'US'),
('LKK', 'Kulik Lake', 'Alaska', 'US'),
('AKN', 'King Salmon', 'Alaska', 'US'),
('IKO', 'Nikolski', 'Alaska', 'US'),
('AKP', 'Anaktuvuk Pass', 'Alaska', 'US'),
('KTN', 'Ketchikan', 'Alaska', 'US'),
('UUK', 'Kuparuk', 'Alaska', 'US'),
('KAL', 'Kaltag', 'Alaska', 'US'),
('AKW', 'Klawock', 'Alaska', 'US'),
('KYK', 'Karluk', 'Alaska', 'US'),
('KLN', 'Larsen Bay', 'Alaska', 'US'),
('KLG', 'Kalskag', 'Alaska', 'US'),
('PTA', 'Port Alsworth', 'Alaska', 'US'),
('LNI', 'Lonely', 'Alaska', 'US'),
('DQH', 'Deadhorse', 'Alaska', 'US'),
('WCR', 'Chandalar Lake', 'Alaska', 'US'),
('LUR', 'Cape Lisburne', 'Alaska', 'US'),
('KMO', 'Manokotak', 'Alaska', 'US'),
('MCG', 'McGrath', 'Alaska', 'US'),
('MDO', 'Middleton Island', 'Alaska', 'US'),
('LMA', 'Minchumina', 'Alaska', 'US'),
('SMK', 'St Michael', 'Alaska', 'US'),
('MLY', 'Manley Hot Springs', 'Alaska', 'US'),
('MOU', 'Mountain Village', 'Alaska', 'US'),
('MRI', 'Anchorage', 'Iowa', 'US'),
('MXY', 'Mccarthy', 'Alaska', 'US'),
('MYU', 'Mekoryuk', 'Alaska', 'US'),
('WNA', 'Napakiak', 'Alaska', 'US'),
('ANC', 'Anchorage', 'Alaska', 'US'),
('ANI', 'Aniak', 'Alaska', 'US'),
('ENN', 'Nenana', 'Alaska', 'US'),
('NNL', 'Nondalton', 'Alaska', 'US'),
('ANN', 'Annette', 'Alaska', 'US'),
('NUL', 'Nulato', 'Alaska', 'US'),
('ANV', 'Anvik', 'Alaska', 'US'),
('KNW', 'New Stuyahok', 'Alaska', 'US'),
('OBU', 'Kobuk', 'Alaska', 'US'),
('PCA', 'Portage Creek', 'Alaska', 'US'),
('HNH', 'Hoonah', 'Alaska', 'US'),
('OME', 'Nome', 'Alaska', 'US'),
('OOK', 'Toksook Bay', 'Alaska', 'US'),
('ORT', 'Northway', 'Alaska', 'US'),
('OTZ', 'Kotzebue', 'Alaska', 'US'),
('NLG', 'Nelson Lagoon', 'Alaska', 'US'),
('PBV', 'St George', 'South-Carolina', 'US'),
('KPC', 'Port Clarence', 'Alaska', 'US'),
('KPV', 'Perryville', 'Alaska', 'US'),
('PSG', 'Petersburg', 'Alaska', 'US'),
('PTH', 'Port Heiden', 'Alaska', 'US'),
('PKA', 'Napaskiak', 'Alaska', 'US'),
('PTU', 'Platinum', 'Alaska', 'US'),
('PIP', 'Pilot Point', 'Alaska', 'US'),
('PHO', 'Point Hope', 'Alaska', 'US'),
('PPC', 'Prospect Creek', 'Alaska', 'US'),
('KWN', 'Quinhagak', 'Alaska', 'US'),
('NUI', 'Nuiqsut', 'Alaska', 'US'),
('ARC', 'Arctic Village', 'Alaska', 'US'),
('RSH', 'Russian Mission', 'Alaska', 'US'),
('RBY', 'Ruby', 'Alaska', 'US'),
('SVA', 'Savoonga', 'Alaska', 'US'),
('SCC', 'Deadhorse', 'Alaska', 'US'),
('SDP', 'Sand Point', 'Alaska', 'US'),
('SHH', 'Shishmaref', 'Alaska', 'US'),
('SIT', 'Sitka', 'Alaska', 'US'),
('WLK', 'Selawik', 'Alaska', 'US'),
('KSM', 'St Mary\'s', 'Alaska', 'US'),
('SNP', 'St Paul Island', 'Alaska', 'US'),
('SOV', 'Seldovia', 'Alaska', 'US'),
('SMU', 'Sheep Mountain', 'Alaska', 'US'),
('UMM', 'Summit', 'Alaska', 'US'),
('SVW', 'Sparrevohn', 'Alaska', 'US'),
('SKW', 'Skwentna', 'Alaska', 'US'),
('SXQ', 'Soldotna', 'Alaska', 'US'),
('SYA', 'Shemya', 'Alaska', 'US'),
('TAL', 'Tanana', 'Alaska', 'US'),
('TNC', 'Tin City', 'Alaska', 'US'),
('TLA', 'Teller', 'Alaska', 'US'),
('TOG', 'Togiak Village', 'Alaska', 'US'),
('TKJ', 'Tok', 'Alaska', 'US'),
('TKA', 'Talkeetna', 'Alaska', 'US'),
('TLJ', 'Takotna', 'Alaska', 'US'),
('ATK', 'Atqasuk', 'Alaska', 'US'),
('AUK', 'Alakanuk', 'Alaska', 'US'),
('UMT', 'Umiat', 'Alaska', 'US'),
('UNK', 'Unalakleet', 'Alaska', 'US'),
('WOW', 'Willow', 'Alaska', 'US'),
('VAK', 'Chevak', 'Alaska', 'US'),
('KVC', 'King Cove', 'Alaska', 'US'),
('VDZ', 'Valdez', 'Alaska', 'US'),
('VEE', 'Venetie', 'Alaska', 'US'),
('KVL', 'Kivalina', 'Alaska', 'US'),
('WBQ', 'Beaver', 'Alaska', 'US'),
('SWD', 'Seward', 'Alaska', 'US'),
('WRG', 'Wrangell', 'Alaska', 'US'),
('AIN', 'Wainwright', 'Alaska', 'US'),
('WMO', 'White Mountain', 'Alaska', 'US'),
('WTK', 'Noatak', 'Alaska', 'US'),
('IYS', 'Wasilla', 'Alaska', 'US'),
('YAK', 'Yakutat', 'Alaska', 'US'),
('AKI', 'Akiak', 'Alaska', 'US'),
('AET', 'Allakaket', 'Alaska', 'US'),
('NCN', 'Chenega', 'Alaska', 'US'),
('CLP', 'Clarks Point', 'Alaska', 'US'),
('ELI', 'Elim', 'Alaska', 'US'),
('KUK', 'Kasigluk', 'Alaska', 'US'),
('KNK', 'Kokhanok', 'Alaska', 'US'),
('KOT', 'Kotlik', 'Alaska', 'US'),
('KTS', 'Brevig Mission', 'Alaska', 'US'),
('KYU', 'Koyukuk', 'Alaska', 'US'),
('KWT', 'Kwethluk', 'Alaska', 'US'),
('ORV', 'Noorvik', 'Alaska', 'US'),
('SKK', 'Shaktoolik', 'Alaska', 'US'),
('WSN', 'South Naknek', 'Alaska', 'US'),
('FYU', 'Fort Yukon', 'Alaska', 'US'),
('BKH', 'Kekaha', 'Hawaii', 'US'),
('HDH', 'Mokuleia', 'Hawaii', 'US'),
('HHI', 'Wahiawa', 'Hawaii', 'US'),
('HNM', 'Hana', 'Hawaii', 'US'),
('JHM', 'Lahaina', 'Hawaii', 'US'),
('JRF', 'Kapolei', 'Hawaii', 'US'),
('KOA', 'Kailua/Kona', 'Hawaii', 'US'),
('LIH', 'Lihue', 'Hawaii', 'US'),
('LUP', 'Kalaupapa', 'Hawaii', 'US'),
('MKK', 'Kaunakakai', 'Hawaii', 'US'),
('MUE', 'Kamuela', 'Hawaii', 'US'),
('NGF', 'Kaneohe', 'Hawaii', 'US'),
('HNL', 'Honolulu', 'Hawaii', 'US'),
('LNY', 'Lanai City', 'Hawaii', 'US'),
('OGG', 'Kahului', 'Hawaii', 'US'),
('PAK', 'Hanapepe', 'Hawaii', 'US'),
('BSF', 'Camp Pohakuloa', 'Hawaii', 'US'),
('ITO', 'Hilo', 'Hawaii', 'US'),
('UPP', 'Hawi', 'Hawaii', 'US'),
('PIZ', 'Point Lay', 'Alaska', 'US'),
('NRT', 'Tokyo', 'Chiba', 'JP'),
('MMJ', 'Matsumoto', 'Nagano', 'JP'),
('IBR', 'Omitama', 'Ibaraki', 'JP'),
('KIX', 'Osaka', 'Osaka', 'JP'),
('SHM', 'Shirahama', 'Wakayama', 'JP'),
('UKB', 'Kobe', 'Hyogo', 'JP'),
('TJH', 'Tajima', 'Hyogo', 'JP'),
('OBO', 'Obihiro', 'Hokkaido', 'JP'),
('CTS', 'Chitose / Tomakomai', 'Hokkaido', 'JP'),
('HKD', 'Hakodate', 'Hokkaido', 'JP'),
('KUH', 'Kushiro', 'Hokkaido', 'JP'),
('MMB', 'Ozora', 'Hokkaido', 'JP'),
('SHB', 'Nakashibetsu', 'Hokkaido', 'JP'),
('OKD', 'Sapporo', 'Hokkaido', 'JP'),
('WKJ', 'Wakkanai', 'Hokkaido', 'JP'),
('IKI', 'Iki', 'Nagasaki', 'JP'),
('UBJ', 'Ube', 'Yamaguchi', 'JP'),
('TSJ', 'Tsushima', 'Nagasaki', 'JP'),
('MBE', 'Monbetsu', 'Hokkaido', 'JP'),
('AKJ', 'Asahikawa', 'Hokkaido', 'JP'),
('RIS', 'Rishiri', 'Hokkaido', 'JP'),
('FUJ', 'Goto', 'Nagasaki', 'JP'),
('FUK', 'Fukuoka', 'Fukuoka', 'JP'),
('KOJ', 'Kagoshima', 'Kagoshima', 'JP'),
('KMI', 'Miyazaki', 'Miyazaki', 'JP'),
('OIT', 'Oita', 'Oita', 'JP'),
('KKJ', 'Kitakyushu', 'Fukuoka', 'JP'),
('HSG', 'Saga', 'Saga', 'JP'),
('KMJ', 'Kumamoto', 'Kumamoto', 'JP'),
('NGS', 'Nagasaki', 'Nagasaki', 'JP'),
('NGO', 'Tokoname', 'Aichi', 'JP'),
('ASJ', 'Amami', 'Kagoshima', 'JP'),
('TKN', 'Tokunoshima', 'Kagoshima', 'JP'),
('NKM', 'Nagoya', 'Aichi', 'JP'),
('QGU', 'Gifu', 'Gifu', 'JP'),
('KMQ', 'Kanazawa', 'Ishikawa', 'JP'),
('OKI', 'Okinoshima', 'Shimane', 'JP'),
('TOY', 'Toyama', 'Toyama', 'JP'),
('NTQ', 'Wajima', 'Ishikawa', 'JP'),
('HIJ', 'Hiroshima', 'Hiroshima', 'JP'),
('OKJ', 'Okayama City', 'Okayama', 'JP'),
('IZO', 'Izumo', 'Shimane', 'JP'),
('YGJ', 'Yonago', 'Tottori', 'JP'),
('IWK', 'Iwakuni', 'Yamaguchi', 'JP'),
('KCZ', 'Nankoku', 'Kochi', 'JP'),
('MYJ', 'Matsuyama', 'Ehime', 'JP'),
('ITM', 'Osaka', 'Hyogo', 'JP'),
('TTJ', 'Tottori', 'Tottori', 'JP'),
('TKS', 'Tokushima', 'Tokushima', 'JP'),
('TAK', 'Takamatsu', 'Kagawa', 'JP'),
('IWJ', 'Masuda', 'Shimane', 'JP'),
('AOJ', 'Aomori', 'Aomori', 'JP'),
('GAJ', 'Yamagata', 'Yamagata', 'JP'),
('FKS', 'Sukagawa', 'Fukushima', 'JP'),
('AXT', 'Akita', 'Akita', 'JP'),
('MSJ', 'Misawa', 'Aomori', 'JP'),
('KIJ', 'Niigata', 'Niigata', 'JP'),
('ONJ', 'Odate', 'Akita', 'JP'),
('SDJ', 'Sendai', 'Miyagi', 'JP'),
('SYO', 'Shonai', 'Yamagata', 'JP'),
('HAC', 'Hachijojima', 'Tokyo', 'JP'),
('OIM', 'Izu Oshima', 'Tokyo', 'JP'),
('MYE', 'Miyakejima', 'Tokyo', 'JP'),
('HND', 'Tokyo', 'Tokyo', 'JP'),
('OKO', 'Fussa', 'Tokyo', 'JP'),
('OKA', 'Naha', 'Okinawa', 'JP'),
('ISG', 'Ishigaki', 'Okinawa', 'JP'),
('KJP', 'Kerama', 'Okinawa', 'JP'),
('MMY', 'Miyako City', 'Okinawa', 'JP'),
('AGJ', 'Aguni', 'Okinawa', 'JP'),
('HTR', 'Hateruma', 'Okinawa', 'JP'),
('DTR', 'Decatur', 'Washington', 'US');